---
exclude_paths:
  - ".tmp/**"
  - "source/.tmp/**"
  - "source/dist/**"
engines:
  csslint:
    exclude_paths:
      - "source/global.css"
  jshint:
    exclude_paths:
      - "source/functions/**"
  psscriptanalyzer:
    exclude_paths:
      - "source/scripts/run-transfer-planner-maintenance.ps1"
      - "source/scripts/run-transfer-planner-refresh.ps1"
