import type { TransferPlannerSourceGapEntry } from "./schema";

// Generated by scripts/planner/build-transfer-planner-source-gap-report.cjs
export const TRANSFER_PLANNER_SOURCE_GAP_ENTRIES: TransferPlannerSourceGapEntry[] = [];
