import type { TransferPlannerSourceGapEntry } from "./schema";

// Generated by scripts/planner/build-transfer-planner-source-gap-report.cjs
export const TRANSFER_PLANNER_SOURCE_GAP_ENTRIES: TransferPlannerSourceGapEntry[] = [
  {
    "ownerType": "major",
    "ownerKey": "uw-seattle-finnish",
    "planId": "uw-seattle-finnish",
    "pathwayId": null,
    "title": "Finnish",
    "campusId": "uw-seattle",
    "sourceCoverageStatus": "source-unfindable",
    "studentVisibility": "hidden",
    "sourceGapReason": "No official primary degree-requirements source candidate met the minimum discovery threshold.",
    "generatedAt": "2026-04-15T04:19:50.142Z",
    "officialLinkCount": 0,
    "candidateCount": 0,
    "suggestedPrimary": null,
    "sourceDiscoveryAttempts": []
  }
];
