# Generated by Django 6.0.3 on 2026-03-14 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostOfAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tuition", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "living_expenses",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("school_type", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("school_id", models.CharField(max_length=100, unique=True)),
                (
                    "test_scores_required",
                    models.CharField(help_text="SAT/ACT requirements", max_length=255),
                ),
                (
                    "english_proficiency_required",
                    models.CharField(
                        help_text="e.g. TOEFL 90+, IELTS 7.0", max_length=255
                    ),
                ),
                ("number_of_students", models.PositiveIntegerField()),
                (
                    "staff_student_rate",
                    models.CharField(help_text="e.g. 1:15", max_length=50),
                ),
                (
                    "gar",
                    models.CharField(
                        max_length=50, verbose_name="Graduation Acceptance Rate"
                    ),
                ),
                ("climate", models.CharField(max_length=255)),
                ("courses_and_classes", models.TextField()),
                ("deadline_dates", models.TextField()),
                ("scholarship_info", models.TextField()),
                ("school_url", models.URLField(max_length=500)),
                (
                    "cost_of_attendance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_details",
                        to="API.costofattendance",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
