# Generated by Django 6.0.3 on 2026-03-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='cost_of_attendance',
        ),
        migrations.AddField(
            model_name='costofattendance',
            name='school',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cost_of_attendance', to='API.school'),
            preserve_default=False,
        ),
    ]
