# Generated by Django 6.0.3 on 2026-03-17 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_school_cost_of_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='english_proficiency',
            field=models.CharField(blank=True, help_text='IELTS/TOEIC/TOEFL scores', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='overall_GPA',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='personal_statement',
            field=models.URLField(default=1, help_text='Link of your personal statement', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='test_score',
            field=models.CharField(blank=True, help_text='SAT/ACT scores', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prefer_climate', models.CharField(max_length=255)),
                ('prefer_location', models.CharField(max_length=255)),
                ('personal_preference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_preference', to='API.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('credit_unit', models.PositiveIntegerField()),
                ('course_GPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('user_transcript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_transcript', to='API.user')),
            ],
        ),
    ]
