# Generated by Django 6.0.3 on 2026-03-17 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_user_email_remove_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='personal_preference',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='user_transcript',
        ),
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='API.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcript',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='API.user'),
            preserve_default=False,
        ),
    ]
