/* eslint-disable */
/* auto-generated by scripts/planner/generate-transfer-planner-source-bootstrap.cjs */

type GreenRiverMajorOption = {
  id: string;
  label: string;
  description?: string;
  searchText: string;
};

export const GREEN_RIVER_MAJOR_OPTIONS: GreenRiverMajorOption[] = [
  {
    "id": "AA-DTA with Concentration in Black Studies",
    "label": "AA-DTA with Concentration in Black Studies",
    "description": "AA-DTA",
    "searchText": "AA-DTA with Concentration in Black Studies AA-DTA"
  },
  {
    "id": "AA-DTA with Concentration in Communication Studies",
    "label": "AA-DTA with Concentration in Communication Studies",
    "description": "AA-DTA",
    "searchText": "AA-DTA with Concentration in Communication Studies AA-DTA"
  },
  {
    "id": "AA-DTA with Concentration in Digital & Broadcast Media",
    "label": "AA-DTA with Concentration in Digital & Broadcast Media",
    "description": "AA-DTA",
    "searchText": "AA-DTA with Concentration in Digital & Broadcast Media AA-DTA"
  },
  {
    "id": "AA-DTA with Concentration in Diversity Studies",
    "label": "AA-DTA with Concentration in Diversity Studies",
    "description": "AA-DTA",
    "searchText": "AA-DTA with Concentration in Diversity Studies AA-DTA"
  },
  {
    "id": "AA-DTA with Concentration in Film Studies",
    "label": "AA-DTA with Concentration in Film Studies",
    "description": "AA-DTA",
    "searchText": "AA-DTA with Concentration in Film Studies AA-DTA"
  },
  {
    "id": "AA-DTA with Concentration in Global Studies",
    "label": "AA-DTA with Concentration in Global Studies",
    "description": "AA-DTA",
    "searchText": "AA-DTA with Concentration in Global Studies AA-DTA"
  },
  {
    "id": "AA-DTA with concentration in Global Studies and Hispanic Studies",
    "label": "AA-DTA with concentration in Global Studies and Hispanic Studies",
    "description": "AA-DTA",
    "searchText": "AA-DTA with concentration in Global Studies and Hispanic Studies AA-DTA"
  },
  {
    "id": "AA-DTA with Concentration in Hispanic Studies",
    "label": "AA-DTA with Concentration in Hispanic Studies",
    "description": "AA-DTA",
    "searchText": "AA-DTA with Concentration in Hispanic Studies AA-DTA"
  },
  {
    "id": "AA-DTA with Concentration in Music",
    "label": "AA-DTA with Concentration in Music",
    "description": "AA-DTA",
    "searchText": "AA-DTA with Concentration in Music AA-DTA"
  },
  {
    "id": "AA-DTA with Concentration in Philosophy",
    "label": "AA-DTA with Concentration in Philosophy",
    "description": "AA-DTA",
    "searchText": "AA-DTA with Concentration in Philosophy AA-DTA"
  },
  {
    "id": "AA-DTA with Concentration in Theatre Arts",
    "label": "AA-DTA with Concentration in Theatre Arts",
    "description": "AA-DTA",
    "searchText": "AA-DTA with Concentration in Theatre Arts AA-DTA"
  },
  {
    "id": "AA-DTA with Emphasis in Professional & Technical Communication",
    "label": "AA-DTA with Emphasis in Professional & Technical Communication",
    "description": "AA-DTA",
    "searchText": "AA-DTA with Emphasis in Professional & Technical Communication AA-DTA"
  },
  {
    "id": "Accounting",
    "label": "Accounting",
    "description": "AAA | Certificate",
    "searchText": "Accounting AAA Certificate"
  },
  {
    "id": "Accounting Clerk",
    "label": "Accounting Clerk",
    "description": "Certificate",
    "searchText": "Accounting Clerk Certificate"
  },
  {
    "id": "Accounting, BAS w/Accounting AAA",
    "label": "Accounting, BAS w/Accounting AAA",
    "description": "BAS",
    "searchText": "Accounting, BAS w/Accounting AAA BAS"
  },
  {
    "id": "Accounting, BAS w/Associate in Business DTA/MRP",
    "label": "Accounting, BAS w/Associate in Business DTA/MRP",
    "description": "BAS",
    "searchText": "Accounting, BAS w/Associate in Business DTA/MRP BAS"
  },
  {
    "id": "Accounting, BAS w/Business Management AAA",
    "label": "Accounting, BAS w/Business Management AAA",
    "description": "BAS",
    "searchText": "Accounting, BAS w/Business Management AAA BAS"
  },
  {
    "id": "Administrative Assistant",
    "label": "Administrative Assistant",
    "description": "AAA | Certificate",
    "searchText": "Administrative Assistant AAA Certificate"
  },
  {
    "id": "Advanced Network Administration and Security",
    "label": "Advanced Network Administration and Security",
    "description": "Certificate",
    "searchText": "Advanced Network Administration and Security Certificate"
  },
  {
    "id": "Aeronautical Science",
    "label": "Aeronautical Science",
    "description": "BAS",
    "searchText": "Aeronautical Science BAS"
  },
  {
    "id": "Anthropology",
    "label": "Anthropology",
    "description": "AA-DTA",
    "searchText": "Anthropology AA-DTA"
  },
  {
    "id": "Applied Management",
    "label": "Applied Management",
    "description": "BAS",
    "searchText": "Applied Management BAS"
  },
  {
    "id": "Associate in Arts-DTA",
    "label": "Associate in Arts-DTA",
    "description": "AA-DTA",
    "searchText": "Associate in Arts-DTA AA-DTA"
  },
  {
    "id": "Associate in Arts-DTA with Concentration in Art History",
    "label": "Associate in Arts-DTA with Concentration in Art History",
    "description": "AA-DTA",
    "searchText": "Associate in Arts-DTA with Concentration in Art History AA-DTA"
  },
  {
    "id": "Associate in Arts-DTA with Concentration in Asian Studies",
    "label": "Associate in Arts-DTA with Concentration in Asian Studies",
    "description": "AA-DTA",
    "searchText": "Associate in Arts-DTA with Concentration in Asian Studies AA-DTA"
  },
  {
    "id": "Associate in Arts-DTA with Concentration in Creative Expression",
    "label": "Associate in Arts-DTA with Concentration in Creative Expression",
    "description": "AA-DTA",
    "searchText": "Associate in Arts-DTA with Concentration in Creative Expression AA-DTA"
  },
  {
    "id": "Associate in Arts-DTA with Concentration in Gender Studies",
    "label": "Associate in Arts-DTA with Concentration in Gender Studies",
    "description": "AA-DTA",
    "searchText": "Associate in Arts-DTA with Concentration in Gender Studies AA-DTA"
  },
  {
    "id": "Associate in Arts-DTA with Concentration in Psychology",
    "label": "Associate in Arts-DTA with Concentration in Psychology",
    "description": "AA-DTA",
    "searchText": "Associate in Arts-DTA with Concentration in Psychology AA-DTA"
  },
  {
    "id": "Associate in Arts-DTA with Emphasis in American Ethnic Studies",
    "label": "Associate in Arts-DTA with Emphasis in American Ethnic Studies",
    "description": "AA-DTA",
    "searchText": "Associate in Arts-DTA with Emphasis in American Ethnic Studies AA-DTA"
  },
  {
    "id": "Associate in Arts-DTA with Emphasis in Creative Writing",
    "label": "Associate in Arts-DTA with Emphasis in Creative Writing",
    "description": "AA-DTA",
    "searchText": "Associate in Arts-DTA with Emphasis in Creative Writing AA-DTA"
  },
  {
    "id": "Associate in Arts-DTA with Emphasis in English Literature",
    "label": "Associate in Arts-DTA with Emphasis in English Literature",
    "description": "AA-DTA",
    "searchText": "Associate in Arts-DTA with Emphasis in English Literature AA-DTA"
  },
  {
    "id": "Associate in Arts-DTA with Emphasis in Geography",
    "label": "Associate in Arts-DTA with Emphasis in Geography",
    "description": "AA-DTA",
    "searchText": "Associate in Arts-DTA with Emphasis in Geography AA-DTA"
  },
  {
    "id": "Associate in Arts-DTA with Emphasis in History",
    "label": "Associate in Arts-DTA with Emphasis in History",
    "description": "AA-DTA",
    "searchText": "Associate in Arts-DTA with Emphasis in History AA-DTA"
  },
  {
    "id": "Associate in Arts-DTA with Emphasis in Political Science",
    "label": "Associate in Arts-DTA with Emphasis in Political Science",
    "description": "AA-DTA",
    "searchText": "Associate in Arts-DTA with Emphasis in Political Science AA-DTA"
  },
  {
    "id": "Associate in Arts-DTA with Emphasis in Sociology",
    "label": "Associate in Arts-DTA with Emphasis in Sociology",
    "description": "AA-DTA",
    "searchText": "Associate in Arts-DTA with Emphasis in Sociology AA-DTA"
  },
  {
    "id": "Associate in Biology, DTA/MRP",
    "label": "Associate in Biology, DTA/MRP",
    "description": "AA-DTA",
    "searchText": "Associate in Biology, DTA/MRP AA-DTA"
  },
  {
    "id": "Associate in Business",
    "label": "Associate in Business",
    "description": "AB-DTA/MRP",
    "searchText": "Associate in Business AB-DTA/MRP"
  },
  {
    "id": "Associate in Computer Science",
    "label": "Associate in Computer Science",
    "description": "ACS-DTA/MRP",
    "searchText": "Associate in Computer Science ACS-DTA/MRP"
  },
  {
    "id": "Associate in Fine Arts",
    "label": "Associate in Fine Arts",
    "description": "AFA",
    "searchText": "Associate in Fine Arts AFA"
  },
  {
    "id": "Associate in Fine Arts, with Concentration in Ceramics",
    "label": "Associate in Fine Arts, with Concentration in Ceramics",
    "description": "Associate",
    "searchText": "Associate in Fine Arts, with Concentration in Ceramics Associate"
  },
  {
    "id": "Associate in Fine Arts, with Concentration in Design",
    "label": "Associate in Fine Arts, with Concentration in Design",
    "description": "Associate",
    "searchText": "Associate in Fine Arts, with Concentration in Design Associate"
  },
  {
    "id": "Associate in Fine Arts, with Concentration in Photography",
    "label": "Associate in Fine Arts, with Concentration in Photography",
    "description": "Associate",
    "searchText": "Associate in Fine Arts, with Concentration in Photography Associate"
  },
  {
    "id": "Associate in Fine Arts, with Concentration in Studio Art",
    "label": "Associate in Fine Arts, with Concentration in Studio Art",
    "description": "Associate",
    "searchText": "Associate in Fine Arts, with Concentration in Studio Art Associate"
  },
  {
    "id": "Associate in Pre-Nursing",
    "label": "Associate in Pre-Nursing",
    "description": "APreN-DTA/MRP",
    "searchText": "Associate in Pre-Nursing APreN-DTA/MRP"
  },
  {
    "id": "Associate in Science Transfer Track 1 - Chemistry",
    "label": "Associate in Science Transfer Track 1 - Chemistry",
    "description": "AST-1",
    "searchText": "Associate in Science Transfer Track 1 - Chemistry AST-1"
  },
  {
    "id": "Associate in Science Transfer Track 1 Biology",
    "label": "Associate in Science Transfer Track 1 Biology",
    "description": "AST-1",
    "searchText": "Associate in Science Transfer Track 1 Biology AST-1"
  },
  {
    "id": "Associate in Science Transfer Track 2-Physics",
    "label": "Associate in Science Transfer Track 2-Physics",
    "description": "AST-2",
    "searchText": "Associate in Science Transfer Track 2-Physics AST-2"
  },
  {
    "id": "Automotive Technology",
    "label": "Automotive Technology",
    "description": "AAS",
    "searchText": "Automotive Technology AAS"
  },
  {
    "id": "Aviation Technology - Aviation Operations Management",
    "label": "Aviation Technology - Aviation Operations Management",
    "description": "Certificate",
    "searchText": "Aviation Technology - Aviation Operations Management Certificate"
  },
  {
    "id": "Aviation Technology, AAS-Air Traffic Control Track",
    "label": "Aviation Technology, AAS-Air Traffic Control Track",
    "description": "AAS",
    "searchText": "Aviation Technology, AAS-Air Traffic Control Track AAS"
  },
  {
    "id": "Aviation Technology, AAS-Airline Dispatch Track",
    "label": "Aviation Technology, AAS-Airline Dispatch Track",
    "description": "AAS",
    "searchText": "Aviation Technology, AAS-Airline Dispatch Track AAS"
  },
  {
    "id": "Aviation Technology, AAS-Aviation Management Track",
    "label": "Aviation Technology, AAS-Aviation Management Track",
    "description": "AAS",
    "searchText": "Aviation Technology, AAS-Aviation Management Track AAS"
  },
  {
    "id": "Aviation Technology, AAS-Commercial Pilot Track",
    "label": "Aviation Technology, AAS-Commercial Pilot Track",
    "description": "AAS",
    "searchText": "Aviation Technology, AAS-Commercial Pilot Track AAS"
  },
  {
    "id": "Aviation Technology: Air Traffic Controller",
    "label": "Aviation Technology: Air Traffic Controller",
    "description": "Certificate",
    "searchText": "Aviation Technology: Air Traffic Controller Certificate"
  },
  {
    "id": "Business Applications Specialist",
    "label": "Business Applications Specialist",
    "description": "AAA | Certificate",
    "searchText": "Business Applications Specialist AAA Certificate"
  },
  {
    "id": "Business Applications Specialist for Small Business",
    "label": "Business Applications Specialist for Small Business",
    "description": "Certificate",
    "searchText": "Business Applications Specialist for Small Business Certificate"
  },
  {
    "id": "Business Management",
    "label": "Business Management",
    "description": "AAA",
    "searchText": "Business Management AAA"
  },
  {
    "id": "Business Management - Business Foundations",
    "label": "Business Management - Business Foundations",
    "description": "Certificate",
    "searchText": "Business Management - Business Foundations Certificate"
  },
  {
    "id": "Business Management - Retail Management",
    "label": "Business Management - Retail Management",
    "description": "Certificate",
    "searchText": "Business Management - Retail Management Certificate"
  },
  {
    "id": "Business Management: Entrepreneurship",
    "label": "Business Management: Entrepreneurship",
    "description": "Certificate",
    "searchText": "Business Management: Entrepreneurship Certificate"
  },
  {
    "id": "Cardiac Monitor/Electrocardiography (EKG) Technician",
    "label": "Cardiac Monitor/Electrocardiography (EKG) Technician",
    "description": "Certificate",
    "searchText": "Cardiac Monitor/Electrocardiography (EKG) Technician Certificate"
  },
  {
    "id": "Carpentry Technology",
    "label": "Carpentry Technology",
    "description": "Certificate",
    "searchText": "Carpentry Technology Certificate"
  },
  {
    "id": "Carpentry Technology Pre-Apprenticeship",
    "label": "Carpentry Technology Pre-Apprenticeship",
    "description": "Certificate",
    "searchText": "Carpentry Technology Pre-Apprenticeship Certificate"
  },
  {
    "id": "Cloud Fundamentals",
    "label": "Cloud Fundamentals",
    "description": "Certificate",
    "searchText": "Cloud Fundamentals Certificate"
  },
  {
    "id": "Court Reporting & Captioning-Scopist/Text Editor",
    "label": "Court Reporting & Captioning-Scopist/Text Editor",
    "description": "Certificate",
    "searchText": "Court Reporting & Captioning-Scopist/Text Editor Certificate"
  },
  {
    "id": "Criminal Justice",
    "label": "Criminal Justice",
    "description": "AAS-T",
    "searchText": "Criminal Justice AAS-T"
  },
  {
    "id": "Criminal Justice - Corrections",
    "label": "Criminal Justice - Corrections",
    "description": "Certificate",
    "searchText": "Criminal Justice - Corrections Certificate"
  },
  {
    "id": "Criminal Justice - Law Enforcement",
    "label": "Criminal Justice - Law Enforcement",
    "description": "Certificate",
    "searchText": "Criminal Justice - Law Enforcement Certificate"
  },
  {
    "id": "Cybersecurity and Networking",
    "label": "Cybersecurity and Networking",
    "description": "AAS-T | BAS",
    "searchText": "Cybersecurity and Networking AAS-T BAS"
  },
  {
    "id": "Data Analytics and Software Development, AAS-T Business Management Track",
    "label": "Data Analytics and Software Development, AAS-T Business Management Track",
    "description": "AAS-T",
    "searchText": "Data Analytics and Software Development, AAS-T Business Management Track AAS-T"
  },
  {
    "id": "Data Analytics and Software Development, AAS-T Software Development Track",
    "label": "Data Analytics and Software Development, AAS-T Software Development Track",
    "description": "AAS-T",
    "searchText": "Data Analytics and Software Development, AAS-T Software Development Track AAS-T"
  },
  {
    "id": "Early Childhood Education",
    "label": "Early Childhood Education",
    "description": "AAS",
    "searchText": "Early Childhood Education AAS"
  },
  {
    "id": "Early Childhood Education (Statewide)",
    "label": "Early Childhood Education (Statewide)",
    "description": "Certificate",
    "searchText": "Early Childhood Education (Statewide) Certificate"
  },
  {
    "id": "Early Childhood Education and Diversity Studies",
    "label": "Early Childhood Education and Diversity Studies",
    "description": "AAS-T",
    "searchText": "Early Childhood Education and Diversity Studies AAS-T"
  },
  {
    "id": "Early Childhood Education Certificate of Specialization",
    "label": "Early Childhood Education Certificate of Specialization",
    "description": "Certificate",
    "searchText": "Early Childhood Education Certificate of Specialization Certificate"
  },
  {
    "id": "Early Childhood Education Paraeducator",
    "label": "Early Childhood Education Paraeducator",
    "description": "AAS-T",
    "searchText": "Early Childhood Education Paraeducator AAS-T"
  },
  {
    "id": "Early Childhood Education: Infant and Child Mental Health",
    "label": "Early Childhood Education: Infant and Child Mental Health",
    "description": "BAS",
    "searchText": "Early Childhood Education: Infant and Child Mental Health BAS"
  },
  {
    "id": "Emergency Room and Patient Care Technician",
    "label": "Emergency Room and Patient Care Technician",
    "description": "Certificate",
    "searchText": "Emergency Room and Patient Care Technician Certificate"
  },
  {
    "id": "Forensic",
    "label": "Forensic",
    "description": "AAS-T",
    "searchText": "Forensic AAS-T"
  },
  {
    "id": "Forensic and Fingerprinting",
    "label": "Forensic and Fingerprinting",
    "description": "Certificate",
    "searchText": "Forensic and Fingerprinting Certificate"
  },
  {
    "id": "Forest Resource Management, BAS Forestry Operations Track",
    "label": "Forest Resource Management, BAS Forestry Operations Track",
    "description": "BAS",
    "searchText": "Forest Resource Management, BAS Forestry Operations Track BAS"
  },
  {
    "id": "Forest Resource Management, BAS Sampling and Assessment Track",
    "label": "Forest Resource Management, BAS Sampling and Assessment Track",
    "description": "BAS",
    "searchText": "Forest Resource Management, BAS Sampling and Assessment Track BAS"
  },
  {
    "id": "Geographic Information Systems",
    "label": "Geographic Information Systems",
    "description": "AAS",
    "searchText": "Geographic Information Systems AAS"
  },
  {
    "id": "Information Technology-Cloud Fundamentals",
    "label": "Information Technology-Cloud Fundamentals",
    "description": "Certificate",
    "searchText": "Information Technology-Cloud Fundamentals Certificate"
  },
  {
    "id": "Information Technology-Fundamentals",
    "label": "Information Technology-Fundamentals",
    "description": "Certificate",
    "searchText": "Information Technology-Fundamentals Certificate"
  },
  {
    "id": "IT Fundamentals",
    "label": "IT Fundamentals",
    "description": "Certificate",
    "searchText": "IT Fundamentals Certificate"
  },
  {
    "id": "IT-Scripting Fundamentals",
    "label": "IT-Scripting Fundamentals",
    "description": "Certificate",
    "searchText": "IT-Scripting Fundamentals Certificate"
  },
  {
    "id": "IT-Security Fundamentals",
    "label": "IT-Security Fundamentals",
    "description": "Certificate",
    "searchText": "IT-Security Fundamentals Certificate"
  },
  {
    "id": "Legal Administrative Assistant",
    "label": "Legal Administrative Assistant",
    "description": "AAA",
    "searchText": "Legal Administrative Assistant AAA"
  },
  {
    "id": "Machining and Manufacturing Technology",
    "label": "Machining and Manufacturing Technology",
    "description": "AAS | Certificate",
    "searchText": "Machining and Manufacturing Technology AAS Certificate"
  },
  {
    "id": "Marketing & Entrepreneurship",
    "label": "Marketing & Entrepreneurship",
    "description": "BAS",
    "searchText": "Marketing & Entrepreneurship BAS"
  },
  {
    "id": "Math Education",
    "label": "Math Education",
    "description": "AM-DTA | AM-DTA/MRP",
    "searchText": "Math Education AM-DTA AM-DTA/MRP"
  },
  {
    "id": "Mechatronics Technician",
    "label": "Mechatronics Technician",
    "description": "AAS",
    "searchText": "Mechatronics Technician AAS"
  },
  {
    "id": "Medical Coding and Reimbursement Specialist",
    "label": "Medical Coding and Reimbursement Specialist",
    "description": "Certificate",
    "searchText": "Medical Coding and Reimbursement Specialist Certificate"
  },
  {
    "id": "Medical Front Office",
    "label": "Medical Front Office",
    "description": "Certificate",
    "searchText": "Medical Front Office Certificate"
  },
  {
    "id": "Medical Office Administration, AAA with emphasis in Front Office",
    "label": "Medical Office Administration, AAA with emphasis in Front Office",
    "description": "AAA",
    "searchText": "Medical Office Administration, AAA with emphasis in Front Office AAA"
  },
  {
    "id": "Medical Office Administration, AAA with emphasis in Medical Coding and Reimbursement",
    "label": "Medical Office Administration, AAA with emphasis in Medical Coding and Reimbursement",
    "description": "AAA",
    "searchText": "Medical Office Administration, AAA with emphasis in Medical Coding and Reimbursement AAA"
  },
  {
    "id": "Medical Office Manager",
    "label": "Medical Office Manager",
    "description": "Certificate",
    "searchText": "Medical Office Manager Certificate"
  },
  {
    "id": "Medical Office Support",
    "label": "Medical Office Support",
    "description": "Certificate",
    "searchText": "Medical Office Support Certificate"
  },
  {
    "id": "Municipal Wastewater Treatment Technology",
    "label": "Municipal Wastewater Treatment Technology",
    "description": "Certificate",
    "searchText": "Municipal Wastewater Treatment Technology Certificate"
  },
  {
    "id": "Natural Resources",
    "label": "Natural Resources",
    "description": "AAS-T",
    "searchText": "Natural Resources AAS-T"
  },
  {
    "id": "Natural Resources-Forestry",
    "label": "Natural Resources-Forestry",
    "description": "AAS",
    "searchText": "Natural Resources-Forestry AAS"
  },
  {
    "id": "Natural Resources-Park Management",
    "label": "Natural Resources-Park Management",
    "description": "AAS",
    "searchText": "Natural Resources-Park Management AAS"
  },
  {
    "id": "Natural Resources-Water Quality",
    "label": "Natural Resources-Water Quality",
    "description": "AAS",
    "searchText": "Natural Resources-Water Quality AAS"
  },
  {
    "id": "Natural Resources-Wildland Fire",
    "label": "Natural Resources-Wildland Fire",
    "description": "AAS",
    "searchText": "Natural Resources-Wildland Fire AAS"
  },
  {
    "id": "Nurse Assistant",
    "label": "Nurse Assistant",
    "description": "Certificate",
    "searchText": "Nurse Assistant Certificate"
  },
  {
    "id": "Occupational Therapy Assistant",
    "label": "Occupational Therapy Assistant",
    "description": "AAS",
    "searchText": "Occupational Therapy Assistant AAS"
  },
  {
    "id": "Occupational Therapy Assistant, AAS Hybrid",
    "label": "Occupational Therapy Assistant, AAS Hybrid",
    "description": "AAS",
    "searchText": "Occupational Therapy Assistant, AAS Hybrid AAS"
  },
  {
    "id": "Paraeducator State",
    "label": "Paraeducator State",
    "description": "Certificate",
    "searchText": "Paraeducator State Certificate"
  },
  {
    "id": "Physical Therapist Assistant",
    "label": "Physical Therapist Assistant",
    "description": "AAS",
    "searchText": "Physical Therapist Assistant AAS"
  },
  {
    "id": "Practical Nursing",
    "label": "Practical Nursing",
    "description": "AAS",
    "searchText": "Practical Nursing AAS"
  },
  {
    "id": "Practical Nursing, AAS Part-time (Hybrid)",
    "label": "Practical Nursing, AAS Part-time (Hybrid)",
    "description": "AAS",
    "searchText": "Practical Nursing, AAS Part-time (Hybrid) AAS"
  },
  {
    "id": "Practical Nursing, AAS Part-time (Online)",
    "label": "Practical Nursing, AAS Part-time (Online)",
    "description": "AAS",
    "searchText": "Practical Nursing, AAS Part-time (Online) AAS"
  },
  {
    "id": "Realtime Reporting: Court Reporting & Captioning",
    "label": "Realtime Reporting: Court Reporting & Captioning",
    "description": "BAS",
    "searchText": "Realtime Reporting: Court Reporting & Captioning BAS"
  },
  {
    "id": "Realtime Transcription",
    "label": "Realtime Transcription",
    "description": "AAA",
    "searchText": "Realtime Transcription AAA"
  },
  {
    "id": "Residential and Light Commercial",
    "label": "Residential and Light Commercial",
    "description": "AAS",
    "searchText": "Residential and Light Commercial AAS"
  },
  {
    "id": "Scripting Fundamentals",
    "label": "Scripting Fundamentals",
    "description": "Certificate",
    "searchText": "Scripting Fundamentals Certificate"
  },
  {
    "id": "Security Fundamentals",
    "label": "Security Fundamentals",
    "description": "Certificate",
    "searchText": "Security Fundamentals Certificate"
  },
  {
    "id": "Software Development",
    "label": "Software Development",
    "description": "BAS",
    "searchText": "Software Development BAS"
  },
  {
    "id": "Transfer Track 2-Bioengineering and Chemical Engineering",
    "label": "Transfer Track 2-Bioengineering and Chemical Engineering",
    "description": "AST-2",
    "searchText": "Transfer Track 2-Bioengineering and Chemical Engineering AST-2"
  },
  {
    "id": "Transfer Track 2/MRP-Civil and Mechanical Engineering",
    "label": "Transfer Track 2/MRP-Civil and Mechanical Engineering",
    "description": "AST-2/MRP",
    "searchText": "Transfer Track 2/MRP-Civil and Mechanical Engineering AST-2/MRP"
  },
  {
    "id": "Transfer Track 2/MRP-Computer and Electrical Engineering",
    "label": "Transfer Track 2/MRP-Computer and Electrical Engineering",
    "description": "AST-2/MRP",
    "searchText": "Transfer Track 2/MRP-Computer and Electrical Engineering AST-2/MRP"
  },
  {
    "id": "Unmanned Aerial Systems, AAS Curriclum Map",
    "label": "Unmanned Aerial Systems, AAS Curriclum Map",
    "description": "AAS",
    "searchText": "Unmanned Aerial Systems, AAS Curriclum Map AAS"
  },
  {
    "id": "Wastewater Technology",
    "label": "Wastewater Technology",
    "description": "AAS",
    "searchText": "Wastewater Technology AAS"
  },
  {
    "id": "Water Distribution Technology",
    "label": "Water Distribution Technology",
    "description": "Certificate",
    "searchText": "Water Distribution Technology Certificate"
  },
  {
    "id": "Water Supply Technology",
    "label": "Water Supply Technology",
    "description": "AAS",
    "searchText": "Water Supply Technology AAS"
  },
  {
    "id": "Welding Technology",
    "label": "Welding Technology",
    "description": "AAS",
    "searchText": "Welding Technology AAS"
  },
  {
    "id": "Welding Technology Certificates",
    "label": "Welding Technology Certificates",
    "description": "Certificate",
    "searchText": "Welding Technology Certificates Certificate"
  }
];

