import { describe, it } from "node:test";
import assert from "node:assert";
import { normalizeMajorTag } from "./opportunities";

describe("normalizeMajorTag", () => {
  it("normalizes a standard string", () => {
    assert.strictEqual(normalizeMajorTag("Computer Science"), "computer science");
  });

  it("handles null and undefined", () => {
    assert.strictEqual(normalizeMajorTag(null), "");
    assert.strictEqual(normalizeMajorTag(undefined), "");
  });

  it("handles non-string values gracefully", () => {
    assert.strictEqual(normalizeMajorTag(12345), "12345");
    assert.strictEqual(normalizeMajorTag({}), "object object");
    assert.strictEqual(normalizeMajorTag(["CS", "Math"]), "cs math");
  });

  it("trims whitespace from start and end", () => {
    assert.strictEqual(normalizeMajorTag("  Math  "), "math");
    assert.strictEqual(normalizeMajorTag("\t\nEngineering\r\n"), "engineering");
  });

  it("converts strings to lowercase", () => {
    assert.strictEqual(normalizeMajorTag("BIOLOGY"), "biology");
    assert.strictEqual(normalizeMajorTag("pRe-MeD"), "pre med");
  });

  it("replaces special characters with spaces", () => {
    assert.strictEqual(normalizeMajorTag("Pre-Med/Nursing!"), "pre med nursing");
    assert.strictEqual(normalizeMajorTag("C++ Programming"), "c programming");
    assert.strictEqual(normalizeMajorTag("CS & Engineering"), "cs engineering");
  });

  it("compresses multiple spaces", () => {
     assert.strictEqual(normalizeMajorTag("Art   History"), "art history");
     assert.strictEqual(normalizeMajorTag("Data    Science"), "data science");
  });

  it("trims spaces generated by special character replacement", () => {
    assert.strictEqual(normalizeMajorTag("!@#Hello World!@#"), "hello world");
    assert.strictEqual(normalizeMajorTag("---Nursing---"), "nursing");
  });
});
