export const TRANSFER_PLANNER_LEGACY_COMPLETED_COURSES_FIELD = "completedCourses";

export const TRANSFER_PLANNER_CURRENT_COURSES_BY_PATH_FIELD =
  "transferPlannerCurrentCoursesByPath";

// Bump this suffix when planner option-group generation changes so older saved
// selections/cache entries cannot hide newly generated option groups.
export const TRANSFER_PLANNER_SELECTED_OPTIONS_BY_PATH_STORAGE_VERSION = "v2";
export const TRANSFER_PLANNER_SELECTED_OPTIONS_BY_PATH_FIELD =
  `transferPlannerSelectedOptionsByPath:${TRANSFER_PLANNER_SELECTED_OPTIONS_BY_PATH_STORAGE_VERSION}`;

export const TRANSFER_PLANNER_SELECTED_PATHWAY_BY_PLAN_FIELD =
  "transferPlannerSelectedPathwayByPlan";
export const TRANSFER_PLANNER_LAST_SELECTED_PLAN_FIELD =
  "transferPlannerLastSelectedPlan";

export const TRANSFER_PLANNER_TRANSCRIPT_COURSES_FIELD =
  "transferPlannerCompletedCourses";
export const TRANSFER_PLANNER_TRANSCRIPT_SOURCE_FIELD =
  "transferPlannerTranscriptSource";
export const TRANSFER_PLANNER_TRANSCRIPT_UPLOADED_AT_FIELD =
  "transferPlannerTranscriptUploadedAt";
export const TRANSFER_PLANNER_TRANSCRIPT_PARSER_VERSION_FIELD =
  "transferPlannerTranscriptParserVersion";
export const TRANSFER_PLANNER_TRANSCRIPT_EARNED_CREDITS_FIELD =
  "transferPlannerTranscriptEarnedCredits";

export const TRANSFER_PLANNER_SELECTION_FIELDS = [
  TRANSFER_PLANNER_CURRENT_COURSES_BY_PATH_FIELD,
  TRANSFER_PLANNER_SELECTED_OPTIONS_BY_PATH_FIELD,
  TRANSFER_PLANNER_SELECTED_PATHWAY_BY_PLAN_FIELD,
  TRANSFER_PLANNER_LAST_SELECTED_PLAN_FIELD,
] as const;

export const TRANSFER_PLANNER_TRANSCRIPT_CACHE_FIELDS = [
  TRANSFER_PLANNER_TRANSCRIPT_COURSES_FIELD,
  TRANSFER_PLANNER_TRANSCRIPT_SOURCE_FIELD,
  TRANSFER_PLANNER_TRANSCRIPT_UPLOADED_AT_FIELD,
  TRANSFER_PLANNER_TRANSCRIPT_PARSER_VERSION_FIELD,
  TRANSFER_PLANNER_TRANSCRIPT_EARNED_CREDITS_FIELD,
] as const;

export const TRANSFER_PLANNER_LOCAL_ONLY_QUESTIONNAIRE_FIELDS = [
  TRANSFER_PLANNER_LEGACY_COMPLETED_COURSES_FIELD,
  ...TRANSFER_PLANNER_TRANSCRIPT_CACHE_FIELDS,
] as const;

export const TRANSFER_PLANNER_QUESTIONNAIRE_STORAGE_FIELDS = [
  TRANSFER_PLANNER_LEGACY_COMPLETED_COURSES_FIELD,
  ...TRANSFER_PLANNER_TRANSCRIPT_CACHE_FIELDS,
  ...TRANSFER_PLANNER_SELECTION_FIELDS,
] as const;

export type TransferPlannerQuestionnaireStorageField =
  (typeof TRANSFER_PLANNER_QUESTIONNAIRE_STORAGE_FIELDS)[number];
