/* eslint-disable */
/* auto-generated by scripts/planner/generate-transfer-planner-course-metadata.cjs */

import type { TransferPlannerNormalizedCourseMetadataEntry } from "./course-metadata";

const { createLazyGeneratedValue } = require("./generated-lazy") as typeof import("./generated-lazy");

const EXPLICIT_SPACED_SUBJECT_ALIASES = new Map<string, string>([
  ["A A", "AA"],
  ["A MATH", "AMATH"],
  ["ART H", "ARTH"],
  ["CHEM E", "CHEME"],
  ["E E", "EE"],
  ["IND E", "INDE"],
  ["M E", "ME"],
]);

const RECOVERABLE_LEADING_SUBJECT_TOKENS = new Set([
  "AND",
  "AS",
  "BOTH",
  "EITHER",
  "IN",
  "OR",
  "PREREQ",
  "PREREQUISITE",
]);

export const TRANSFER_PLANNER_GENERATED_COURSE_SUBJECT_CODES = [
  "AA",
  "AAS",
  "ACCT",
  "ACCT&",
  "ACCTG",
  "AES",
  "AFRAM",
  "AIS",
  "AMATH",
  "AMES",
  "ANTH",
  "ANTH&",
  "AP",
  "ARAB",
  "ARCH",
  "ARCHY",
  "ARCTIC",
  "ART",
  "ART&",
  "ARTH",
  "ASIAN",
  "ASL",
  "ASTR",
  "ASTR&",
  "ATECH",
  "ATMOS",
  "AVIA",
  "BBECN",
  "BBIO",
  "BBUS",
  "BCHEM",
  "BCMS",
  "BCORE",
  "BDATA",
  "BE",
  "BEARTH",
  "BECON",
  "BEDUC",
  "BEE",
  "BENG",
  "BENGR",
  "BES",
  "BH",
  "BHLTH",
  "BHS",
  "BIMD",
  "BIME",
  "BIOA",
  "BIOC",
  "BIOEN",
  "BIOL",
  "BIOL&",
  "BIOST",
  "BIS",
  "BISAES",
  "BISCLA",
  "BISGST",
  "BISGWS",
  "BISIA",
  "BISLEP",
  "BISMCS",
  "BISPSY",
  "BISSTS",
  "BMATH",
  "BME",
  "BNURS",
  "BNURSE",
  "BPHYS",
  "BST",
  "BTAC",
  "BULGR",
  "BUS",
  "BUS&",
  "BWRIT",
  "CARDIO",
  "CARP",
  "CEE",
  "CEP",
  "CESI",
  "CFRM",
  "CHEM",
  "CHEM&",
  "CHEME",
  "CHID",
  "CHIN",
  "CHSTU",
  "CJ",
  "CJ&",
  "CLAS",
  "CLIT",
  "CM",
  "CMS",
  "CMST",
  "CMST&",
  "COLL",
  "COM",
  "COMMLD",
  "COOP",
  "CRC",
  "CS",
  "CS&",
  "CSE",
  "CSS",
  "CSSS",
  "CSSSKL",
  "CZECH",
  "DANCE",
  "DANISH",
  "DESIGN",
  "DISST",
  "DRAMA",
  "DRMA",
  "DRMA&",
  "ECE",
  "ECED",
  "ECED&",
  "ECFS",
  "ECON",
  "ECON&",
  "EDC&I",
  "EDLPS",
  "EDPSY",
  "EDSPE",
  "EDUC",
  "EDUC&",
  "EE",
  "ELCBUS",
  "ENGL",
  "ENGL&",
  "ENGR",
  "ENGR&",
  "ENTRE",
  "ENVH",
  "ENVIR",
  "EPI",
  "ERTECH",
  "ESRM",
  "ESS",
  "ETHICS",
  "FHL",
  "FILM",
  "FIN",
  "FINN",
  "FISH",
  "FRCH",
  "FRCH&",
  "FRENCH",
  "GENOME",
  "GEOG",
  "GEOG&",
  "GEOL",
  "GEOL&",
  "GERM&",
  "GERMAN",
  "GH",
  "GLITS",
  "GRDSCH",
  "GREEK",
  "GWSS",
  "HCDE",
  "HEALTH",
  "HINDI",
  "HIST",
  "HIST&",
  "HSERV",
  "HSTAA",
  "HSTAM",
  "HSTAS",
  "HSTCMP",
  "HSTEU",
  "HSTLAC",
  "HSTRY",
  "HUMAN",
  "IBUS",
  "IECMH",
  "INDE",
  "INDIV",
  "INDUS",
  "INFO",
  "IPM",
  "IS",
  "IT",
  "JAPAN",
  "JAPN",
  "JAPN&",
  "JEWST",
  "JOURN",
  "JSIS",
  "JSISA",
  "JSISB",
  "KAZAKH",
  "KOREAN",
  "LARCH",
  "LAS",
  "LATIN",
  "LING",
  "LSJ",
  "MARBIO",
  "MATH",
  "MATH&",
  "ME",
  "MELC",
  "MFG",
  "MGMT",
  "MICROM",
  "MKTG",
  "MNURS",
  "MODHEB",
  "MOLENG",
  "MSE",
  "MTX",
  "MUHST",
  "MUSAP",
  "MUSC",
  "MUSC&",
  "MUSED",
  "MUSEN",
  "MUSIC",
  "MUSICP",
  "NATRS",
  "NCLIN",
  "NEUSCI",
  "NME",
  "NORW",
  "NURS",
  "NUTR",
  "NUTR&",
  "OCEA&",
  "OCEAN",
  "OPMGT",
  "OTA",
  "PHG",
  "PHIL",
  "PHIL&",
  "PHLEB",
  "PHOTO",
  "PHYS",
  "PHYS&",
  "PNURSE",
  "POLS",
  "POLS&",
  "POLSH",
  "PORT",
  "PRSAN",
  "PSYC",
  "PSYC&",
  "PSYCH",
  "PTA",
  "PUBPOL",
  "QMETH",
  "QSCI",
  "RE",
  "READ",
  "RELIG",
  "RUSS",
  "SASIA",
  "SBSE",
  "SCAND",
  "SDEV",
  "SEFS",
  "SLAVIC",
  "SLVN",
  "SMEA",
  "SNKRT",
  "SOC",
  "SOC&",
  "SOCW",
  "SOCWF",
  "SPAN",
  "SPAN&",
  "SPH",
  "SPHSC",
  "SPLING",
  "STAT",
  "STMATH",
  "SWED",
  "TACCT",
  "TAMST",
  "TANTH",
  "TARTS",
  "TBANLT",
  "TBECON",
  "TBGEN",
  "TBIOL",
  "TBIOMD",
  "TBUS",
  "TCE",
  "TCES",
  "TCHEM",
  "TCHIN",
  "TCOM",
  "TCORE",
  "TCRIM",
  "TCSL",
  "TCSS",
  "TECE",
  "TECON",
  "TEDSP",
  "TEDUC",
  "TEE",
  "TEGL",
  "TESC",
  "TEST",
  "TFILM",
  "TGEOG",
  "TGEOS",
  "TGH",
  "TGIS",
  "THIST",
  "THLEAD",
  "THLTH",
  "TIAS",
  "TINFO",
  "TINST",
  "TKISH",
  "TLAW",
  "TLAX",
  "TLIT",
  "TMATH",
  "TME",
  "TMGMT",
  "TMKTG",
  "TNPRFT",
  "TNURS",
  "TPHIL",
  "TPHYS",
  "TPOLS",
  "TPSYCH",
  "TRELIG",
  "TSOC",
  "TSOCWF",
  "TSPAN",
  "TSTAT",
  "TSUD",
  "TUDE",
  "TURB",
  "TWOMN",
  "TWRT",
  "UKR",
  "URBAN",
  "URDU",
  "UYGUR",
  "UZBEK",
  "WELD",
] as const;

const TRANSFER_PLANNER_GENERATED_COURSE_METADATA_PARTITION_KEYS = [
  "grc-acct",
  "grc-ames",
  "grc-anth",
  "grc-ap",
  "grc-arab",
  "grc-art",
  "grc-astr",
  "grc-atech",
  "grc-avia",
  "grc-biol",
  "grc-bnurse",
  "grc-btac",
  "grc-bus",
  "grc-cardio",
  "grc-carp",
  "grc-chem",
  "grc-cj",
  "grc-cmst",
  "grc-coll",
  "grc-coop",
  "grc-crc",
  "grc-cs",
  "grc-dance",
  "grc-drma",
  "grc-eced",
  "grc-econ",
  "grc-educ",
  "grc-engl",
  "grc-engr",
  "grc-ertech",
  "grc-film",
  "grc-frch",
  "grc-geog",
  "grc-geol",
  "grc-germ",
  "grc-health",
  "grc-hist",
  "grc-human",
  "grc-indus",
  "grc-info",
  "grc-it",
  "grc-japn",
  "grc-journ",
  "grc-las",
  "grc-math",
  "grc-mfg",
  "grc-mgmt",
  "grc-mnurs",
  "grc-mtx",
  "grc-musc",
  "grc-natrs",
  "grc-nutr",
  "grc-ocea",
  "grc-ota",
  "grc-phil",
  "grc-phleb",
  "grc-photo",
  "grc-phys",
  "grc-pnurse",
  "grc-pols",
  "grc-psyc",
  "grc-pta",
  "grc-read",
  "grc-sdev",
  "grc-soc",
  "grc-span",
  "grc-weld",
  "uw-bothell-bbecn",
  "uw-bothell-bbio",
  "uw-bothell-bbus",
  "uw-bothell-bchem",
  "uw-bothell-bcore",
  "uw-bothell-bdata",
  "uw-bothell-bearth",
  "uw-bothell-beduc",
  "uw-bothell-bee",
  "uw-bothell-bengr",
  "uw-bothell-bes",
  "uw-bothell-bhlth",
  "uw-bothell-bhs",
  "uw-bothell-bimd",
  "uw-bothell-bis",
  "uw-bothell-bisaes",
  "uw-bothell-biscla",
  "uw-bothell-bisgst",
  "uw-bothell-bisgws",
  "uw-bothell-bisia",
  "uw-bothell-bislep",
  "uw-bothell-bismcs",
  "uw-bothell-bispsy",
  "uw-bothell-bissts",
  "uw-bothell-bmath",
  "uw-bothell-bme",
  "uw-bothell-bnurs",
  "uw-bothell-bphys",
  "uw-bothell-bst",
  "uw-bothell-bwrit",
  "uw-bothell-css",
  "uw-bothell-cssskl",
  "uw-bothell-elcbus",
  "uw-bothell-stmath",
  "uw-seattle-aa",
  "uw-seattle-aas",
  "uw-seattle-acctg",
  "uw-seattle-aes",
  "uw-seattle-afram",
  "uw-seattle-ais",
  "uw-seattle-amath",
  "uw-seattle-anth",
  "uw-seattle-arab",
  "uw-seattle-arch",
  "uw-seattle-archy",
  "uw-seattle-arctic",
  "uw-seattle-art",
  "uw-seattle-arth",
  "uw-seattle-asian",
  "uw-seattle-asl",
  "uw-seattle-astr",
  "uw-seattle-atmos",
  "uw-seattle-bcms",
  "uw-seattle-be",
  "uw-seattle-becon",
  "uw-seattle-beng",
  "uw-seattle-bh",
  "uw-seattle-bime",
  "uw-seattle-bioa",
  "uw-seattle-bioc",
  "uw-seattle-bioen",
  "uw-seattle-biol",
  "uw-seattle-biost",
  "uw-seattle-bulgr",
  "uw-seattle-cee",
  "uw-seattle-cep",
  "uw-seattle-cesi",
  "uw-seattle-cfrm",
  "uw-seattle-chem",
  "uw-seattle-cheme",
  "uw-seattle-chid",
  "uw-seattle-chin",
  "uw-seattle-chstu",
  "uw-seattle-clas",
  "uw-seattle-clit",
  "uw-seattle-cm",
  "uw-seattle-cms",
  "uw-seattle-com",
  "uw-seattle-commld",
  "uw-seattle-cse",
  "uw-seattle-csss",
  "uw-seattle-czech",
  "uw-seattle-dance",
  "uw-seattle-danish",
  "uw-seattle-design",
  "uw-seattle-disst",
  "uw-seattle-drama",
  "uw-seattle-ece",
  "uw-seattle-ecfs",
  "uw-seattle-econ",
  "uw-seattle-edc-i",
  "uw-seattle-edlps",
  "uw-seattle-edpsy",
  "uw-seattle-edspe",
  "uw-seattle-educ",
  "uw-seattle-ee",
  "uw-seattle-engl",
  "uw-seattle-engr",
  "uw-seattle-entre",
  "uw-seattle-envh",
  "uw-seattle-envir",
  "uw-seattle-epi",
  "uw-seattle-esrm",
  "uw-seattle-ess",
  "uw-seattle-ethics",
  "uw-seattle-fhl",
  "uw-seattle-fin",
  "uw-seattle-finn",
  "uw-seattle-fish",
  "uw-seattle-french",
  "uw-seattle-genome",
  "uw-seattle-geog",
  "uw-seattle-german",
  "uw-seattle-gh",
  "uw-seattle-glits",
  "uw-seattle-grdsch",
  "uw-seattle-greek",
  "uw-seattle-gwss",
  "uw-seattle-hcde",
  "uw-seattle-hindi",
  "uw-seattle-hserv",
  "uw-seattle-hstaa",
  "uw-seattle-hstam",
  "uw-seattle-hstas",
  "uw-seattle-hstcmp",
  "uw-seattle-hsteu",
  "uw-seattle-hstlac",
  "uw-seattle-hstry",
  "uw-seattle-ibus",
  "uw-seattle-iecmh",
  "uw-seattle-inde",
  "uw-seattle-indiv",
  "uw-seattle-info",
  "uw-seattle-ipm",
  "uw-seattle-is",
  "uw-seattle-japan",
  "uw-seattle-jewst",
  "uw-seattle-jsis",
  "uw-seattle-jsisa",
  "uw-seattle-jsisb",
  "uw-seattle-kazakh",
  "uw-seattle-korean",
  "uw-seattle-larch",
  "uw-seattle-latin",
  "uw-seattle-ling",
  "uw-seattle-lsj",
  "uw-seattle-marbio",
  "uw-seattle-math",
  "uw-seattle-me",
  "uw-seattle-melc",
  "uw-seattle-mgmt",
  "uw-seattle-microm",
  "uw-seattle-mktg",
  "uw-seattle-modheb",
  "uw-seattle-moleng",
  "uw-seattle-mse",
  "uw-seattle-muhst",
  "uw-seattle-musap",
  "uw-seattle-mused",
  "uw-seattle-musen",
  "uw-seattle-music",
  "uw-seattle-musicp",
  "uw-seattle-nclin",
  "uw-seattle-neusci",
  "uw-seattle-nme",
  "uw-seattle-norw",
  "uw-seattle-nurs",
  "uw-seattle-nutr",
  "uw-seattle-ocean",
  "uw-seattle-opmgt",
  "uw-seattle-phg",
  "uw-seattle-phil",
  "uw-seattle-phys",
  "uw-seattle-pols",
  "uw-seattle-polsh",
  "uw-seattle-port",
  "uw-seattle-prsan",
  "uw-seattle-psych",
  "uw-seattle-pubpol",
  "uw-seattle-qmeth",
  "uw-seattle-qsci",
  "uw-seattle-re",
  "uw-seattle-relig",
  "uw-seattle-russ",
  "uw-seattle-sasia",
  "uw-seattle-sbse",
  "uw-seattle-scand",
  "uw-seattle-sefs",
  "uw-seattle-slavic",
  "uw-seattle-slvn",
  "uw-seattle-smea",
  "uw-seattle-snkrt",
  "uw-seattle-soc",
  "uw-seattle-socw",
  "uw-seattle-socwf",
  "uw-seattle-span",
  "uw-seattle-sph",
  "uw-seattle-sphsc",
  "uw-seattle-spling",
  "uw-seattle-stat",
  "uw-seattle-swed",
  "uw-seattle-tkish",
  "uw-seattle-ukr",
  "uw-seattle-urban",
  "uw-seattle-urdu",
  "uw-seattle-uygur",
  "uw-seattle-uzbek",
  "uw-tacoma-tacct",
  "uw-tacoma-tamst",
  "uw-tacoma-tanth",
  "uw-tacoma-tarts",
  "uw-tacoma-tbanlt",
  "uw-tacoma-tbecon",
  "uw-tacoma-tbgen",
  "uw-tacoma-tbiol",
  "uw-tacoma-tbiomd",
  "uw-tacoma-tbus",
  "uw-tacoma-tce",
  "uw-tacoma-tces",
  "uw-tacoma-tchem",
  "uw-tacoma-tchin",
  "uw-tacoma-tcom",
  "uw-tacoma-tcore",
  "uw-tacoma-tcrim",
  "uw-tacoma-tcsl",
  "uw-tacoma-tcss",
  "uw-tacoma-tece",
  "uw-tacoma-tecon",
  "uw-tacoma-tedsp",
  "uw-tacoma-teduc",
  "uw-tacoma-tee",
  "uw-tacoma-tegl",
  "uw-tacoma-tesc",
  "uw-tacoma-test",
  "uw-tacoma-tfilm",
  "uw-tacoma-tgeog",
  "uw-tacoma-tgeos",
  "uw-tacoma-tgh",
  "uw-tacoma-tgis",
  "uw-tacoma-thist",
  "uw-tacoma-thlead",
  "uw-tacoma-thlth",
  "uw-tacoma-tias",
  "uw-tacoma-tinfo",
  "uw-tacoma-tinst",
  "uw-tacoma-tlaw",
  "uw-tacoma-tlax",
  "uw-tacoma-tlit",
  "uw-tacoma-tmath",
  "uw-tacoma-tme",
  "uw-tacoma-tmgmt",
  "uw-tacoma-tmktg",
  "uw-tacoma-tnprft",
  "uw-tacoma-tnurs",
  "uw-tacoma-tphil",
  "uw-tacoma-tphys",
  "uw-tacoma-tpols",
  "uw-tacoma-tpsych",
  "uw-tacoma-trelig",
  "uw-tacoma-tsoc",
  "uw-tacoma-tsocwf",
  "uw-tacoma-tspan",
  "uw-tacoma-tstat",
  "uw-tacoma-tsud",
  "uw-tacoma-tude",
  "uw-tacoma-turb",
  "uw-tacoma-twomn",
  "uw-tacoma-twrt",
] as const;

function normalizeGeneratedCourseMetadataCode(value: string | null | undefined) {
  return String(value ?? "")
    .toUpperCase()
    .replace(/\s+/g, " ")
    .trim();
}

function normalizeGeneratedCourseMetadataLookupCode(value: string | null | undefined) {
  const normalized = normalizeGeneratedCourseMetadataCode(value);
  const match = normalized.match(/^([A-Z&]+(?: [A-Z&]+)*) (\d{3}(?:\.\d+)?[A-Z]?)$/);
  if (!match) {
    return normalized;
  }

  const knownSubjectCodes = new Set<string>(TRANSFER_PLANNER_GENERATED_COURSE_SUBJECT_CODES);
  let subjectTokens = match[1].split(" ").filter(Boolean);
  while (
    subjectTokens.length > 1 &&
    RECOVERABLE_LEADING_SUBJECT_TOKENS.has(subjectTokens[0])
  ) {
    const candidateTokens = subjectTokens.slice(1);
    const candidateSpacedSubject = candidateTokens.join(" ");
    const candidateCollapsedSubject = candidateTokens.join("");
    if (
      knownSubjectCodes.has(candidateSpacedSubject) ||
      knownSubjectCodes.has(candidateCollapsedSubject)
    ) {
      subjectTokens = candidateTokens;
      continue;
    }
    break;
  }

  const spacedSubject = subjectTokens.join(" ");
  const explicitAlias = EXPLICIT_SPACED_SUBJECT_ALIASES.get(spacedSubject);
  if (explicitAlias) {
    return `${explicitAlias} ${match[2]}`;
  }

  const collapsedSubject = subjectTokens.join("");
  const normalizedSubject =
    subjectTokens.every((token) => token.length === 1) ||
    (subjectTokens.length > 1 &&
      knownSubjectCodes.has(collapsedSubject) &&
      !knownSubjectCodes.has(spacedSubject))
      ? collapsedSubject
      : spacedSubject;

  return `${normalizedSubject} ${match[2]}`;
}

function getGeneratedCourseMetadataSubjectCode(value: string | null | undefined) {
  const match = normalizeGeneratedCourseMetadataLookupCode(value).match(/^([A-Z&]+(?: [A-Z&]+)*)\s+\d/);
  return match?.[1] ?? "unknown";
}

function slugifyGeneratedCourseMetadataKey(value: string | null | undefined) {
  return String(value ?? "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function getTransferPlannerGeneratedCourseMetadataPartitionKey(
  schoolId: string | null | undefined,
  code: string | null | undefined
) {
  const schoolPart = slugifyGeneratedCourseMetadataKey(schoolId) || "unknown-school";
  const subjectPart =
    slugifyGeneratedCourseMetadataKey(getGeneratedCourseMetadataSubjectCode(code)) ||
    "unknown-subject";
  return `${schoolPart}-${subjectPart}`;
}

function loadTransferPlannerGeneratedCourseMetadataPartitionIndex() {
  return require("./course-metadata.generated/partition-index.generated.json") as Record<string, string>;
}

const TRANSFER_PLANNER_GENERATED_COURSE_METADATA_PARTITION_INDEX =
  createLazyGeneratedValue<Record<string, string>>(
    loadTransferPlannerGeneratedCourseMetadataPartitionIndex,
    {} as Record<string, string>
  );

function loadTransferPlannerGeneratedCourseMetadataPartition(partitionKey: string) {
  switch (partitionKey) {
    case "grc-acct":
      return require("./course-metadata.generated/entries-by-school-subject/grc-acct.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-ames":
      return require("./course-metadata.generated/entries-by-school-subject/grc-ames.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-anth":
      return require("./course-metadata.generated/entries-by-school-subject/grc-anth.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-ap":
      return require("./course-metadata.generated/entries-by-school-subject/grc-ap.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-arab":
      return require("./course-metadata.generated/entries-by-school-subject/grc-arab.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-art":
      return require("./course-metadata.generated/entries-by-school-subject/grc-art.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-astr":
      return require("./course-metadata.generated/entries-by-school-subject/grc-astr.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-atech":
      return require("./course-metadata.generated/entries-by-school-subject/grc-atech.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-avia":
      return require("./course-metadata.generated/entries-by-school-subject/grc-avia.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-biol":
      return require("./course-metadata.generated/entries-by-school-subject/grc-biol.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-bnurse":
      return require("./course-metadata.generated/entries-by-school-subject/grc-bnurse.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-btac":
      return require("./course-metadata.generated/entries-by-school-subject/grc-btac.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-bus":
      return require("./course-metadata.generated/entries-by-school-subject/grc-bus.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-cardio":
      return require("./course-metadata.generated/entries-by-school-subject/grc-cardio.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-carp":
      return require("./course-metadata.generated/entries-by-school-subject/grc-carp.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-chem":
      return require("./course-metadata.generated/entries-by-school-subject/grc-chem.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-cj":
      return require("./course-metadata.generated/entries-by-school-subject/grc-cj.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-cmst":
      return require("./course-metadata.generated/entries-by-school-subject/grc-cmst.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-coll":
      return require("./course-metadata.generated/entries-by-school-subject/grc-coll.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-coop":
      return require("./course-metadata.generated/entries-by-school-subject/grc-coop.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-crc":
      return require("./course-metadata.generated/entries-by-school-subject/grc-crc.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-cs":
      return require("./course-metadata.generated/entries-by-school-subject/grc-cs.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-dance":
      return require("./course-metadata.generated/entries-by-school-subject/grc-dance.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-drma":
      return require("./course-metadata.generated/entries-by-school-subject/grc-drma.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-eced":
      return require("./course-metadata.generated/entries-by-school-subject/grc-eced.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-econ":
      return require("./course-metadata.generated/entries-by-school-subject/grc-econ.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-educ":
      return require("./course-metadata.generated/entries-by-school-subject/grc-educ.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-engl":
      return require("./course-metadata.generated/entries-by-school-subject/grc-engl.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-engr":
      return require("./course-metadata.generated/entries-by-school-subject/grc-engr.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-ertech":
      return require("./course-metadata.generated/entries-by-school-subject/grc-ertech.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-film":
      return require("./course-metadata.generated/entries-by-school-subject/grc-film.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-frch":
      return require("./course-metadata.generated/entries-by-school-subject/grc-frch.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-geog":
      return require("./course-metadata.generated/entries-by-school-subject/grc-geog.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-geol":
      return require("./course-metadata.generated/entries-by-school-subject/grc-geol.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-germ":
      return require("./course-metadata.generated/entries-by-school-subject/grc-germ.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-health":
      return require("./course-metadata.generated/entries-by-school-subject/grc-health.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-hist":
      return require("./course-metadata.generated/entries-by-school-subject/grc-hist.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-human":
      return require("./course-metadata.generated/entries-by-school-subject/grc-human.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-indus":
      return require("./course-metadata.generated/entries-by-school-subject/grc-indus.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-info":
      return require("./course-metadata.generated/entries-by-school-subject/grc-info.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-it":
      return require("./course-metadata.generated/entries-by-school-subject/grc-it.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-japn":
      return require("./course-metadata.generated/entries-by-school-subject/grc-japn.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-journ":
      return require("./course-metadata.generated/entries-by-school-subject/grc-journ.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-las":
      return require("./course-metadata.generated/entries-by-school-subject/grc-las.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-math":
      return require("./course-metadata.generated/entries-by-school-subject/grc-math.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-mfg":
      return require("./course-metadata.generated/entries-by-school-subject/grc-mfg.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-mgmt":
      return require("./course-metadata.generated/entries-by-school-subject/grc-mgmt.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-mnurs":
      return require("./course-metadata.generated/entries-by-school-subject/grc-mnurs.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-mtx":
      return require("./course-metadata.generated/entries-by-school-subject/grc-mtx.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-musc":
      return require("./course-metadata.generated/entries-by-school-subject/grc-musc.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-natrs":
      return require("./course-metadata.generated/entries-by-school-subject/grc-natrs.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-nutr":
      return require("./course-metadata.generated/entries-by-school-subject/grc-nutr.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-ocea":
      return require("./course-metadata.generated/entries-by-school-subject/grc-ocea.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-ota":
      return require("./course-metadata.generated/entries-by-school-subject/grc-ota.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-phil":
      return require("./course-metadata.generated/entries-by-school-subject/grc-phil.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-phleb":
      return require("./course-metadata.generated/entries-by-school-subject/grc-phleb.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-photo":
      return require("./course-metadata.generated/entries-by-school-subject/grc-photo.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-phys":
      return require("./course-metadata.generated/entries-by-school-subject/grc-phys.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-pnurse":
      return require("./course-metadata.generated/entries-by-school-subject/grc-pnurse.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-pols":
      return require("./course-metadata.generated/entries-by-school-subject/grc-pols.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-psyc":
      return require("./course-metadata.generated/entries-by-school-subject/grc-psyc.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-pta":
      return require("./course-metadata.generated/entries-by-school-subject/grc-pta.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-read":
      return require("./course-metadata.generated/entries-by-school-subject/grc-read.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-sdev":
      return require("./course-metadata.generated/entries-by-school-subject/grc-sdev.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-soc":
      return require("./course-metadata.generated/entries-by-school-subject/grc-soc.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-span":
      return require("./course-metadata.generated/entries-by-school-subject/grc-span.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "grc-weld":
      return require("./course-metadata.generated/entries-by-school-subject/grc-weld.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bbecn":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bbecn.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bbio":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bbio.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bbus":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bbus.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bchem":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bchem.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bcore":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bcore.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bdata":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bdata.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bearth":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bearth.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-beduc":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-beduc.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bee":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bee.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bengr":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bengr.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bes":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bes.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bhlth":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bhlth.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bhs":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bhs.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bimd":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bimd.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bis":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bis.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bisaes":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bisaes.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-biscla":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-biscla.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bisgst":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bisgst.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bisgws":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bisgws.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bisia":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bisia.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bislep":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bislep.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bismcs":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bismcs.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bispsy":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bispsy.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bissts":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bissts.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bmath":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bmath.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bme":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bme.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bnurs":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bnurs.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bphys":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bphys.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bst":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bst.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-bwrit":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-bwrit.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-css":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-css.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-cssskl":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-cssskl.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-elcbus":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-elcbus.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-bothell-stmath":
      return require("./course-metadata.generated/entries-by-school-subject/uw-bothell-stmath.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-aa":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-aa.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-aas":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-aas.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-acctg":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-acctg.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-aes":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-aes.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-afram":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-afram.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-ais":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-ais.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-amath":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-amath.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-anth":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-anth.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-arab":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-arab.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-arch":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-arch.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-archy":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-archy.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-arctic":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-arctic.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-art":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-art.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-arth":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-arth.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-asian":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-asian.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-asl":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-asl.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-astr":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-astr.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-atmos":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-atmos.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-bcms":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-bcms.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-be":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-be.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-becon":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-becon.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-beng":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-beng.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-bh":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-bh.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-bime":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-bime.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-bioa":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-bioa.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-bioc":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-bioc.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-bioen":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-bioen.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-biol":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-biol.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-biost":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-biost.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-bulgr":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-bulgr.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-cee":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-cee.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-cep":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-cep.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-cesi":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-cesi.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-cfrm":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-cfrm.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-chem":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-chem.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-cheme":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-cheme.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-chid":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-chid.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-chin":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-chin.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-chstu":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-chstu.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-clas":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-clas.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-clit":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-clit.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-cm":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-cm.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-cms":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-cms.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-com":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-com.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-commld":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-commld.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-cse":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-cse.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-csss":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-csss.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-czech":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-czech.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-dance":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-dance.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-danish":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-danish.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-design":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-design.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-disst":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-disst.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-drama":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-drama.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-ece":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-ece.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-ecfs":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-ecfs.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-econ":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-econ.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-edc-i":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-edc-i.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-edlps":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-edlps.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-edpsy":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-edpsy.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-edspe":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-edspe.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-educ":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-educ.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-ee":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-ee.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-engl":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-engl.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-engr":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-engr.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-entre":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-entre.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-envh":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-envh.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-envir":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-envir.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-epi":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-epi.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-esrm":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-esrm.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-ess":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-ess.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-ethics":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-ethics.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-fhl":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-fhl.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-fin":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-fin.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-finn":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-finn.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-fish":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-fish.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-french":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-french.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-genome":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-genome.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-geog":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-geog.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-german":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-german.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-gh":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-gh.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-glits":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-glits.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-grdsch":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-grdsch.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-greek":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-greek.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-gwss":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-gwss.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-hcde":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-hcde.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-hindi":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-hindi.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-hserv":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-hserv.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-hstaa":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-hstaa.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-hstam":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-hstam.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-hstas":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-hstas.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-hstcmp":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-hstcmp.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-hsteu":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-hsteu.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-hstlac":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-hstlac.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-hstry":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-hstry.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-ibus":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-ibus.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-iecmh":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-iecmh.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-inde":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-inde.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-indiv":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-indiv.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-info":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-info.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-ipm":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-ipm.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-is":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-is.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-japan":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-japan.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-jewst":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-jewst.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-jsis":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-jsis.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-jsisa":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-jsisa.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-jsisb":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-jsisb.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-kazakh":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-kazakh.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-korean":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-korean.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-larch":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-larch.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-latin":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-latin.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-ling":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-ling.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-lsj":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-lsj.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-marbio":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-marbio.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-math":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-math.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-me":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-me.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-melc":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-melc.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-mgmt":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-mgmt.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-microm":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-microm.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-mktg":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-mktg.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-modheb":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-modheb.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-moleng":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-moleng.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-mse":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-mse.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-muhst":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-muhst.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-musap":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-musap.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-mused":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-mused.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-musen":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-musen.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-music":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-music.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-musicp":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-musicp.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-nclin":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-nclin.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-neusci":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-neusci.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-nme":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-nme.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-norw":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-norw.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-nurs":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-nurs.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-nutr":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-nutr.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-ocean":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-ocean.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-opmgt":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-opmgt.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-phg":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-phg.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-phil":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-phil.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-phys":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-phys.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-pols":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-pols.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-polsh":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-polsh.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-port":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-port.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-prsan":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-prsan.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-psych":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-psych.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-pubpol":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-pubpol.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-qmeth":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-qmeth.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-qsci":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-qsci.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-re":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-re.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-relig":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-relig.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-russ":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-russ.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-sasia":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-sasia.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-sbse":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-sbse.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-scand":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-scand.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-sefs":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-sefs.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-slavic":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-slavic.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-slvn":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-slvn.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-smea":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-smea.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-snkrt":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-snkrt.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-soc":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-soc.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-socw":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-socw.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-socwf":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-socwf.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-span":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-span.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-sph":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-sph.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-sphsc":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-sphsc.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-spling":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-spling.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-stat":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-stat.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-swed":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-swed.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-tkish":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-tkish.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-ukr":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-ukr.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-urban":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-urban.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-urdu":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-urdu.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-uygur":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-uygur.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-seattle-uzbek":
      return require("./course-metadata.generated/entries-by-school-subject/uw-seattle-uzbek.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tacct":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tacct.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tamst":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tamst.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tanth":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tanth.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tarts":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tarts.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tbanlt":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tbanlt.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tbecon":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tbecon.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tbgen":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tbgen.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tbiol":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tbiol.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tbiomd":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tbiomd.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tbus":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tbus.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tce":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tce.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tces":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tces.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tchem":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tchem.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tchin":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tchin.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tcom":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tcom.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tcore":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tcore.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tcrim":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tcrim.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tcsl":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tcsl.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tcss":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tcss.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tece":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tece.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tecon":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tecon.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tedsp":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tedsp.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-teduc":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-teduc.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tee":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tee.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tegl":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tegl.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tesc":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tesc.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-test":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-test.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tfilm":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tfilm.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tgeog":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tgeog.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tgeos":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tgeos.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tgh":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tgh.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tgis":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tgis.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-thist":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-thist.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-thlead":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-thlead.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-thlth":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-thlth.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tias":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tias.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tinfo":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tinfo.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tinst":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tinst.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tlaw":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tlaw.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tlax":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tlax.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tlit":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tlit.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tmath":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tmath.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tme":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tme.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tmgmt":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tmgmt.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tmktg":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tmktg.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tnprft":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tnprft.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tnurs":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tnurs.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tphil":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tphil.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tphys":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tphys.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tpols":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tpols.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tpsych":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tpsych.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-trelig":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-trelig.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tsoc":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tsoc.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tsocwf":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tsocwf.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tspan":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tspan.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tstat":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tstat.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tsud":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tsud.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-tude":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-tude.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-turb":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-turb.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-twomn":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-twomn.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    case "uw-tacoma-twrt":
      return require("./course-metadata.generated/entries-by-school-subject/uw-tacoma-twrt.generated.json") as TransferPlannerNormalizedCourseMetadataEntry[];
    default:
      return [] as TransferPlannerNormalizedCourseMetadataEntry[];
  }
}

function loadTransferPlannerGeneratedCourseMetadata() {
  return TRANSFER_PLANNER_GENERATED_COURSE_METADATA_PARTITION_KEYS.flatMap((partitionKey) =>
    loadTransferPlannerGeneratedCourseMetadataPartition(partitionKey)
  ) as TransferPlannerNormalizedCourseMetadataEntry[];
}

export const TRANSFER_PLANNER_GENERATED_COURSE_METADATA =
  createLazyGeneratedValue<TransferPlannerNormalizedCourseMetadataEntry[]>(
    loadTransferPlannerGeneratedCourseMetadata,
    []
  );

export function getTransferPlannerGeneratedCourseMetadata() {
  return TRANSFER_PLANNER_GENERATED_COURSE_METADATA;
}

export function getTransferPlannerGeneratedCourseMetadataEntry(
  schoolId: string,
  code: string
) {
  const normalizedSchoolId = String(schoolId ?? "");
  const normalizedCode = normalizeGeneratedCourseMetadataLookupCode(code);
  const lookupKey = `${normalizedSchoolId}|${normalizedCode}`;
  const partitionKey =
    TRANSFER_PLANNER_GENERATED_COURSE_METADATA_PARTITION_INDEX[lookupKey] ??
    getTransferPlannerGeneratedCourseMetadataPartitionKey(normalizedSchoolId, normalizedCode);
  return (
    loadTransferPlannerGeneratedCourseMetadataPartition(partitionKey).find(
      (entry) =>
        entry.schoolId === normalizedSchoolId &&
        normalizeGeneratedCourseMetadataLookupCode(entry.code) === normalizedCode
    ) ?? null
  );
}

export function getTransferPlannerGeneratedCourseSubjectCodes() {
  return [...TRANSFER_PLANNER_GENERATED_COURSE_SUBJECT_CODES];
}
