/* eslint-disable */
/* auto-generated by scripts/planner/parse-transfer-planner-requirement-sources.cjs */

export const TRANSFER_PLANNER_GENERATED_PROGRAM_APPROVED_COURSE_FILTERS = [
  {
    "filterId": "CE_APPROVED_MATH_SCIENCE",
    "filterKey": "computer-engineering-math-science",
    "label": "CE-approved Math/Science",
    "ownerIds": [
      "uw-seattle-computer-engineering"
    ],
    "campusId": "uw-seattle",
    "officialSourceUrl": "https://www.cs.washington.edu/wp-content/uploads/2025/02/CompE_degreq_dec24v2.pdf",
    "sourceUrl": "https://www.cs.washington.edu/wp-content/uploads/2025/02/CompE_degreq_dec24v2.pdf",
    "sourceRole": "primary-degree-requirements",
    "approvedUwCourseCodes": [
      "AMATH 351",
      "ASTR 301",
      "ASTR 321",
      "ASTR 322",
      "ASTR 323",
      "ASTR 423",
      "ASTR 480",
      "ATMOS 301",
      "ATMOS 321",
      "ATMOS 370",
      "ATMOS 380",
      "ATMOS 451",
      "ATMOS 452",
      "ATMOS 460",
      "BIOL 162",
      "BIOL 180",
      "BIOL 200",
      "BIOL 220",
      "BIOL 325",
      "BIOL 333",
      "BIOL 340",
      "BIOL 354",
      "BIOL 355",
      "BIOL 356",
      "BIOL 401",
      "BIOL 402",
      "BIOL 403",
      "BIOL 405",
      "BIOL 407",
      "BIOL 408",
      "BIOL 409",
      "BIOL 411",
      "BIOL 412",
      "BIOL 413",
      "BIOL 414",
      "BIOL 415",
      "BIOL 425",
      "BIOL 426",
      "BIOL 427",
      "BIOL 433",
      "BIOL 434",
      "BIOL 435",
      "BIOL 437",
      "BIOL 440",
      "BIOL 441",
      "BIOL 442",
      "BIOL 443",
      "BIOL 444",
      "BIOL 446",
      "BIOL 452",
      "BIOL 454",
      "BIOL 455",
      "BIOL 459",
      "BIOL 462",
      "BIOL 463",
      "BIOL 464",
      "BIOL 471",
      "BIOL 472",
      "BIOL 473",
      "BIOL 474",
      "BIOL 475",
      "BIOL 476",
      "BIOL 477",
      "BIOL 479",
      "BIOL 480",
      "CHEM 142",
      "CHEM 143",
      "CHEM 144",
      "CHEM 145",
      "CHEM 152",
      "CHEM 155",
      "CHEM 162",
      "CHEM 165",
      "CHEM 220",
      "CHEM 221",
      "CHEM 223",
      "CHEM 224",
      "CHEM 237",
      "CHEM 238",
      "CHEM 239",
      "CHEM 241",
      "CHEM 242",
      "CHEM 312",
      "CHEM 317",
      "CHEM 321",
      "ESS 311",
      "ESS 313",
      "ESS 403",
      "ESS 413",
      "ESS 414",
      "ESS 415",
      "ESS 424",
      "ESS 431",
      "ESS 437",
      "ESS 438",
      "ESS 458",
      "ESS 464",
      "ESS 466",
      "ESS 467",
      "ESS 471",
      "MATH 207",
      "MATH 209",
      "MATH 318",
      "MATH 334",
      "MATH 335",
      "MATH 394",
      "PHYS 116",
      "PHYS 119",
      "PHYS 123",
      "PHYS 143",
      "PHYS 224",
      "PHYS 225",
      "PHYS 227",
      "PHYS 228",
      "PHYS 231",
      "PHYS 232",
      "PHYS 315",
      "PHYS 321",
      "PHYS 322",
      "PHYS 323",
      "PHYS 324",
      "PHYS 325",
      "PHYS 328",
      "PHYS 331",
      "PHYS 334",
      "PHYS 335",
      "PHYS 407",
      "PHYS 408",
      "PHYS 421",
      "PHYS 422",
      "PHYS 423",
      "PHYS 424",
      "PHYS 425",
      "PHYS 426",
      "PHYS 434",
      "PHYS 460",
      "STAT 391",
      "STAT 394"
    ],
    "genericCategoryTags": [
      "NSC",
      "NW"
    ],
    "aliases": [
      "computer-engineering-math-science",
      "ce-approved-math-science",
      "ce-math-science",
      "computer-engineering-approved-math-science",
      "CE_APPROVED_MATH_SCIENCE"
    ],
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "Computer Engineering Math/Science bucket",
      "Computer Engineering Natural Science Requirement",
      "Biology",
      "Chemistry",
      "Physics",
      "Earth & Space Sciences",
      "Astronomy",
      "Atmospheric Science"
    ],
    "sourceEvidenceLines": [
      "3 to 6 additional credits of Math/Science (to (3-6) any level in the College of Engineering such as",
      "bring the total to 41) chosen from approved",
      "ENGR, HCDE, ECE, etc) to 40 , not including the",
      "natural science courses for Computer Engineering on",
      "the CSE website, as well as STAT 391, 394, MATH Fundamentals section above .",
      "207, 209, 318, 334, 335, 394, AMATH 351, 353.",
      "(This is needed only if courses outside of CSE and",
      "Engineering are used to meet the electives requirement above.)",
      "Computer Engineering Natural Science Requirement",
      "Chemistry 142/145",
      "Biology 180",
      "Biology",
      "BIOL 162 (5 credits from Biology AP)",
      "BIOL 180",
      "BIOL 200",
      "BIOL 220",
      "Must take one of the three above as a prerequisite to the following (when required)",
      "BIOL 325, 333, 340, 354, 355, 356, 401, 402, 403, 405, 407, 408, 409, 411, 412, 413, 414, 415, 425, 426, 427, 433, 434, 435, 437, 440, 441, 442, 443, 444, 446, 452, 454, 455, 459, 462, 463, 464, 471, 472, 473, 474, 475, 476, 477, 479, 480.",
      "Chemistry",
      "CHEM 142, 143, 144, 145, 152, 155, 162, 165, 220, 221, 223, 224, 237, 238, 239, 241, 242, 312, 317, 321, other graded 400 level courses by petition.",
      "Physics",
      "PHYS 116/119, (but no credit for both 116 and 123),123, 143, 224, 225, 227, 228, 231, 232, 315, 321, 322, 323, 324, 325, 328, 331, 334, 335, 407, 408, 421, 422, 423, 424, 425, 426, 434, 460.",
      "Earth & Space Sciences",
      "ESS 311, 313, 403, 413, 414, 415, 424, 431, 437, 438, 458, 464, 466, 467, 471.",
      "Astronomy",
      "ASTR 301, 321, 322, 323, 423, 480, 480.",
      "Atmospheric Science",
      "ATMOS: 301, 321, 370, 380, 451, 452, 460.",
      "Check with a CSE adviser about courses that are not included in this list, but which require Physics 121, Chemistry 142/145, Biology 180 as a pre-requisite."
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "24d6b58477cdaf7afae48cd5852efb7a2a2eaf203994d7cd06602db35dbc75ff"
  },
  {
    "filterId": "CE_APPROVED_NATURAL_SCIENCE",
    "filterKey": "computer-engineering-natural-science",
    "label": "CE-approved Natural Science",
    "ownerIds": [
      "uw-seattle-computer-engineering"
    ],
    "campusId": "uw-seattle",
    "officialSourceUrl": "https://www.cs.washington.edu/academics/undergraduate/degree-requirements/courses/",
    "sourceUrl": "https://www.cs.washington.edu/academics/undergraduate/degree-requirements/courses/",
    "sourceRole": "approved-course-list",
    "approvedUwCourseCodes": [
      "ASTR 301",
      "ASTR 321",
      "ASTR 322",
      "ASTR 323",
      "ASTR 423",
      "ASTR 480",
      "ATMOS 301",
      "ATMOS 321",
      "ATMOS 370",
      "ATMOS 380",
      "ATMOS 451",
      "ATMOS 452",
      "ATMOS 460",
      "BIOL 162",
      "BIOL 180",
      "BIOL 200",
      "BIOL 220",
      "BIOL 325",
      "BIOL 333",
      "BIOL 340",
      "BIOL 354",
      "BIOL 355",
      "BIOL 356",
      "BIOL 401",
      "BIOL 402",
      "BIOL 403",
      "BIOL 405",
      "BIOL 407",
      "BIOL 408",
      "BIOL 409",
      "BIOL 411",
      "BIOL 412",
      "BIOL 413",
      "BIOL 414",
      "BIOL 415",
      "BIOL 425",
      "BIOL 426",
      "BIOL 427",
      "BIOL 433",
      "BIOL 434",
      "BIOL 435",
      "BIOL 437",
      "BIOL 440",
      "BIOL 441",
      "BIOL 442",
      "BIOL 443",
      "BIOL 444",
      "BIOL 446",
      "BIOL 452",
      "BIOL 454",
      "BIOL 455",
      "BIOL 459",
      "BIOL 462",
      "BIOL 463",
      "BIOL 464",
      "BIOL 471",
      "BIOL 472",
      "BIOL 473",
      "BIOL 474",
      "BIOL 475",
      "BIOL 476",
      "BIOL 477",
      "BIOL 479",
      "BIOL 480",
      "CHEM 142",
      "CHEM 143",
      "CHEM 144",
      "CHEM 145",
      "CHEM 152",
      "CHEM 155",
      "CHEM 162",
      "CHEM 165",
      "CHEM 220",
      "CHEM 221",
      "CHEM 223",
      "CHEM 224",
      "CHEM 237",
      "CHEM 238",
      "CHEM 239",
      "CHEM 241",
      "CHEM 242",
      "CHEM 312",
      "CHEM 317",
      "CHEM 321",
      "ESS 311",
      "ESS 313",
      "ESS 403",
      "ESS 413",
      "ESS 414",
      "ESS 415",
      "ESS 424",
      "ESS 431",
      "ESS 437",
      "ESS 438",
      "ESS 458",
      "ESS 464",
      "ESS 466",
      "ESS 467",
      "ESS 471",
      "PHYS 116",
      "PHYS 119",
      "PHYS 123",
      "PHYS 143",
      "PHYS 224",
      "PHYS 225",
      "PHYS 227",
      "PHYS 228",
      "PHYS 231",
      "PHYS 232",
      "PHYS 315",
      "PHYS 321",
      "PHYS 322",
      "PHYS 323",
      "PHYS 324",
      "PHYS 325",
      "PHYS 328",
      "PHYS 331",
      "PHYS 334",
      "PHYS 335",
      "PHYS 407",
      "PHYS 408",
      "PHYS 421",
      "PHYS 422",
      "PHYS 423",
      "PHYS 424",
      "PHYS 425",
      "PHYS 426",
      "PHYS 434",
      "PHYS 460"
    ],
    "approvedUwCourseGroups": [
      [
        "CHEM 142",
        "CHEM 145"
      ]
    ],
    "petitionOnlyNotes": [
      "Must take one of the three above as a prerequisite to the following (when required)",
      "CHEM 142, 143, 144, 145, 152, 155, 162, 165, 220, 221, 223, 224, 237, 238, 239, 241, 242, 312, 317, 321, other graded 400 level courses by petition.",
      "Check with a CSE adviser about courses that are not included in this list, but which require Physics 121, Chemistry 142/145, Biology 180 as a pre-requisite."
    ],
    "genericCategoryTags": [
      "NSC",
      "NW"
    ],
    "aliases": [
      "computer-engineering-natural-science",
      "ce-approved-natural-science",
      "ce-approved-natural-sciences",
      "ce-natural-science",
      "ce-approved-nsc",
      "CE_APPROVED_NATURAL_SCIENCE"
    ],
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "Computer Engineering Natural Science Requirement",
      "Biology",
      "Chemistry",
      "Physics",
      "Earth & Space Sciences",
      "Astronomy",
      "Atmospheric Science"
    ],
    "sourceEvidenceLines": [
      "Computer Engineering Natural Science Requirement",
      "Chemistry 142/145",
      "Biology 180",
      "Biology",
      "BIOL 162 (5 credits from Biology AP)",
      "BIOL 180",
      "BIOL 200",
      "BIOL 220",
      "Must take one of the three above as a prerequisite to the following (when required)",
      "BIOL 325, 333, 340, 354, 355, 356, 401, 402, 403, 405, 407, 408, 409, 411, 412, 413, 414, 415, 425, 426, 427, 433, 434, 435, 437, 440, 441, 442, 443, 444, 446, 452, 454, 455, 459, 462, 463, 464, 471, 472, 473, 474, 475, 476, 477, 479, 480.",
      "Chemistry",
      "CHEM 142, 143, 144, 145, 152, 155, 162, 165, 220, 221, 223, 224, 237, 238, 239, 241, 242, 312, 317, 321, other graded 400 level courses by petition.",
      "Physics",
      "PHYS 116/119, (but no credit for both 116 and 123),123, 143, 224, 225, 227, 228, 231, 232, 315, 321, 322, 323, 324, 325, 328, 331, 334, 335, 407, 408, 421, 422, 423, 424, 425, 426, 434, 460.",
      "Earth & Space Sciences",
      "ESS 311, 313, 403, 413, 414, 415, 424, 431, 437, 438, 458, 464, 466, 467, 471.",
      "Astronomy",
      "ASTR 301, 321, 322, 323, 423, 480, 480.",
      "Atmospheric Science",
      "ATMOS: 301, 321, 370, 380, 451, 452, 460.",
      "Check with a CSE adviser about courses that are not included in this list, but which require Physics 121, Chemistry 142/145, Biology 180 as a pre-requisite."
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "9cccb66114f28b7fca015388c1216547346a1fcb7afa0dfad1c287a4289835fd"
  },
  {
    "filterId": "CS_APPROVED_SCIENCE",
    "filterKey": "computer-science-approved-science",
    "label": "CS-approved Science",
    "ownerIds": [
      "uw-seattle-computer-science",
      "uw-seattle-computer-science:pathway:data-science-option"
    ],
    "campusId": "uw-seattle",
    "officialSourceUrl": "https://www.cs.washington.edu/academics/undergraduate/degree-requirements/courses/",
    "sourceUrl": "https://www.cs.washington.edu/academics/undergraduate/degree-requirements/courses/",
    "sourceRole": "approved-course-list",
    "approvedUwCourseCodes": [
      "BIOL 162",
      "BIOL 180",
      "CHEM 142",
      "CHEM 143",
      "CHEM 145",
      "PHYS 116",
      "PHYS 119",
      "PHYS 121",
      "PHYS 141"
    ],
    "approvedUwCourseGroups": [
      [
        "PHYS 121",
        "PHYS 141"
      ],
      [
        "CHEM 142",
        "CHEM 143",
        "CHEM 145"
      ],
      [
        "PHYS 116",
        "PHYS 119"
      ]
    ],
    "genericCategoryTags": [
      "NSC",
      "NW"
    ],
    "aliases": [
      "computer-science-approved-science",
      "cs-approved-science",
      "cs-approved-natural-science",
      "computer-science-natural-science",
      "CS_APPROVED_SCIENCE"
    ],
    "allowEquivalencyRulesWithAdditionalTargets": true,
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "Computer Science Natural Science Requirement"
    ],
    "sourceEvidenceLines": [
      "Computer Science Natural Science Requirement",
      "Physics 121/141",
      "Chemistry 142, 143 or 145",
      "Biology 180",
      "Biology 162 (AP credit)",
      "Physics 116 *and* Physics 119 – generally from AP credit. If you have not taken science, PHYS 121 is recommended as Phys 116 is the 3rd course in a series."
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "9a1bee58f7ba9b0bce2ce340a1f7d62d36ff989ed42e85ddbf3d48135bd08da0"
  },
  {
    "filterId": "UW_BOTHELL_EDUCATIONAL_STUDIES_ELEMENTARY_EDUCATION_UNITED_STATES_GOVERNMENT_OR_CIVICS_GEOGRAPHY_OR_ECONOMICS_COURSE_APPROVED_COURSES",
    "filterKey": "uw-bothell-educational-studies-elementary-education-united-states-government-or-civics-geography-or-economics-course-approved-courses",
    "label": "Uw Bothell Educational Studies Elementary Education United States Government Or Civics Geography Or Economics Course Approved Courses",
    "ownerIds": [
      "uw-bothell-educational-studies-elementary-education",
      "uw-bothell-educational-studies-elementary-education:pathway:cecl-concentration",
      "uw-bothell-educational-studies-elementary-education:pathway:education-studies-elementary-education-option",
      "uw-bothell-educational-studies-elementary-education:pathway:esol-concentration",
      "uw-bothell-educational-studies-elementary-education:pathway:lede-concentration"
    ],
    "campusId": "uw-bothell",
    "officialSourceUrl": "https://www.uwb.edu/education/undergraduate/elementary-education/degree-requirements",
    "sourceUrl": "https://www.uwb.edu/education/undergraduate/elementary-education/degree-requirements",
    "sourceRole": "primary-degree-requirements",
    "approvedUwCourseCodes": [
      "BEDUC 205",
      "BEDUC 210",
      "BEDUC 300",
      "BEDUC 310"
    ],
    "aliases": [
      "uw-bothell-educational-studies-elementary-education-united-states-government-or-civics-geography-or-economics-course-approved-courses"
    ],
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "Elementary Education Endorsement Academic Breadth Courses"
    ],
    "sourceEvidenceLines": [
      "Elementary Education Endorsement Academic Breadth Courses",
      "B EDUC 205 Education & Equity in the United States (DIV, SSc)",
      "B EDUC 210 Teaching & Learning in a Multicultural Society (DIV, SSc)",
      "B EDUC 300 Research & Educational Knowledge (W)",
      "B EDUC 310 Theories of Learning, Culture & Identity (SSc)"
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "f1726e77420625140ac9d877a350201a7de813a01a566373ecd0f1ec003a080e"
  },
  {
    "filterId": "UW_BOTHELL_PHYSICS_BA_SELECT_FROM_THE_APPROVED_LIST_OF_BPHYS_COURSES",
    "filterKey": "uw-bothell-physics-ba-select-from-the-approved-list-of-bphys-courses",
    "label": "Uw Bothell Physics Ba Select From The Approved List Of Bphys Courses",
    "ownerIds": [
      "uw-bothell-physics-ba",
      "uw-bothell-physics-ba:pathway:ba-route"
    ],
    "campusId": "uw-bothell",
    "officialSourceUrl": "https://www.uwb.edu/stem/undergraduate/majors/physics/curriculum",
    "sourceUrl": "https://www.uwb.edu/stem/undergraduate/majors/physics/curriculum",
    "sourceRole": "primary-degree-requirements",
    "approvedUwCourseCodes": [
      "ENGL 131"
    ],
    "aliases": [
      "uw-bothell-physics-ba-select-from-the-approved-list-of-bphys-courses"
    ],
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "Core Courses",
      "Mathematics",
      "Physics",
      "Biology",
      "Chemistry"
    ],
    "sourceEvidenceLines": [
      "Core Courses",
      "Mathematics",
      "Physics",
      "Biology",
      "Chemistry",
      "English Composition (C) – 5 credits"
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "d43d7b1e131f07e7f0e075f79588a1a43586a404b44f432c0cdfb65fd6d9849b"
  },
  {
    "filterId": "UW_BOTHELL_PHYSICS_BS_SELECT_FROM_THE_APPROVED_LIST_OF_BPHYS_COURSES",
    "filterKey": "uw-bothell-physics-bs-select-from-the-approved-list-of-bphys-courses",
    "label": "Uw Bothell Physics Bs Select From The Approved List Of Bphys Courses",
    "ownerIds": [
      "uw-bothell-physics-bs"
    ],
    "campusId": "uw-bothell",
    "officialSourceUrl": "https://www.uwb.edu/stem/undergraduate/majors/physics/curriculum",
    "sourceUrl": "https://www.uwb.edu/stem/undergraduate/majors/physics/curriculum",
    "sourceRole": "primary-degree-requirements",
    "approvedUwCourseCodes": [
      "ENGL 131"
    ],
    "aliases": [
      "uw-bothell-physics-bs-select-from-the-approved-list-of-bphys-courses"
    ],
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "Core Courses",
      "Mathematics",
      "Physics",
      "Biology",
      "Chemistry"
    ],
    "sourceEvidenceLines": [
      "Core Courses",
      "Mathematics",
      "Physics",
      "Biology",
      "Chemistry",
      "English Composition (C) – 5 credits"
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "078a630917eda1f0443915840674c95c290594831558cb025b9cb1b7edd9dea9"
  },
  {
    "filterId": "UW_SEATTLE_ART_ART_PREFIX_COURSES",
    "filterKey": "uw-seattle-art-art-prefix-courses",
    "label": "Uw Seattle Art Art Prefix Courses",
    "ownerIds": [
      "uw-seattle-art"
    ],
    "campusId": "uw-seattle",
    "officialSourceUrl": "https://www.washington.edu/students/gencat/program/S/Art+ArtHistory+Design-105.html",
    "sourceUrl": "https://www.washington.edu/students/gencat/program/S/Art+ArtHistory+Design-105.html",
    "sourceRole": "official-catalog",
    "approvedUwCourseCodes": [
      "ART 101",
      "ART 140",
      "ART 190",
      "ART 191",
      "ART 233",
      "ART 240",
      "ART 245",
      "ART 246",
      "ART 253",
      "ART 260",
      "ART 272",
      "ART 280",
      "ART 285",
      "ART 290",
      "ART 292",
      "ART 440",
      "ART 453",
      "ART 494"
    ],
    "aliases": [
      "uw-seattle-art-art-prefix-courses"
    ],
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "Students pursuing a Bachelor of Arts degree may choose courses which progress through a structured curriculum in Painting + Drawing, or choose to gain skills in a variety of media (interdisciplinary Visual Arts), which can then be synthesized into a coherent approach to visual expression. Students develop a deep understanding of historical and contemporary issues related to artistic practice, art history and visual culture, while benefiting from broad study across diverse learning communities at the University of Washington. Bachelor of Arts students are prepared for a range of career paths in the creative arts through experiential learning."
    ],
    "sourceEvidenceLines": [
      "Students pursuing a Bachelor of Arts degree may choose courses which progress through a structured curriculum in Painting + Drawing, or choose to gain skills in a variety of media (interdisciplinary Visual Arts), which can then be synthesized into a coherent approach to visual expression. Students develop a deep understanding of historical and contemporary issues related to artistic practice, art history and visual culture, while benefiting from broad study across diverse learning communities at the University of Washington. Bachelor of Arts students are prepared for a range of career paths in the creative arts through experiential learning.",
      "15 credits introductory art classes: ART 101, ART 140, ART 190, ART 191, ART 233, ART 240, ART 245, ART 246, ART 253, ART 260, ART 272, ART 280, ART 285, ART 290, ART 292",
      "10 credits from ART 400, ART 440, ART 453, ART 494"
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "e0d0515597f35c332c27a4b4c77bd1360f07659ed88a0c6a231e107c5c520afe"
  },
  {
    "filterId": "UW_SEATTLE_ART_HISTORY_ARTH_PREFIX_COURSES",
    "filterKey": "uw-seattle-art-history-arth-prefix-courses",
    "label": "Uw Seattle Art History Arth Prefix Courses",
    "ownerIds": [
      "uw-seattle-art-history"
    ],
    "campusId": "uw-seattle",
    "officialSourceUrl": "https://www.washington.edu/students/gencat/program/S/Art+ArtHistory+Design-105.html",
    "sourceUrl": "https://www.washington.edu/students/gencat/program/S/Art+ArtHistory+Design-105.html",
    "sourceRole": "official-catalog",
    "approvedUwCourseCodes": [
      "ARTH 200",
      "ARTH 201",
      "ARTH 202",
      "ARTH 203",
      "ARTH 204",
      "ARTH 206",
      "ARTH 209",
      "ARTH 212",
      "ARTH 214",
      "ARTH 220",
      "ARTH 233",
      "ARTH 270",
      "ARTH 272",
      "ARTH 273",
      "ARTH 290",
      "ARTH 309",
      "ARTH 310",
      "ARTH 311",
      "ARTH 312",
      "ARTH 314",
      "ARTH 333",
      "ARTH 361",
      "ARTH 373",
      "ARTH 380",
      "ARTH 381",
      "ARTH 390",
      "ARTH 391",
      "ARTH 400",
      "ARTH 412",
      "ARTH 413",
      "ARTH 414",
      "ARTH 419",
      "ARTH 435",
      "ARTH 471",
      "ARTH 473",
      "ARTH 484",
      "ARTH 488",
      "ARTH 491",
      "ARTH 492",
      "ARTH 494"
    ],
    "aliases": [
      "uw-seattle-art-history-arth-prefix-courses"
    ],
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "10 credits of ARTH prefix courses"
    ],
    "sourceEvidenceLines": [
      "10 credits of ARTH prefix courses",
      "Parsed approved course codes from https://www.washington.edu/students/gencat/program/S/Art+ArtHistory+Design-105.html."
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "10cb8e2446563043920af81f278b4ca494c5f78d43d948ac0055f59edd97da5f"
  },
  {
    "filterId": "UW_SEATTLE_BUSINESS_ADMINISTRATION_THERE_IS_NO_NEED_TO_SUBMIT_FOSTER_COURSES_ALL_APPROVED_COURSES_ARE_LISTED_ON_THE_BUSINESS_MINOR_WEBSITE_UNDER_CURRICULUM",
    "filterKey": "uw-seattle-business-administration-there-is-no-need-to-submit-foster-courses-all-approved-courses-are-listed-on-the-business-minor-website-under-curriculum",
    "label": "Uw Seattle Business Administration There Is No Need To Submit Foster Courses All Approved Courses Are Listed On The Business Minor Website Under Curriculum",
    "ownerIds": [
      "uw-seattle-business-administration:pathway:ba-route"
    ],
    "campusId": "uw-seattle",
    "officialSourceUrl": "https://foster.uw.edu/academics/degree-programs/undergraduate-programs/curriculum/",
    "sourceUrl": "https://foster.uw.edu/academics/degree-programs/undergraduate-programs/curriculum/",
    "sourceRole": "primary-degree-requirements",
    "approvedUwCourseCodes": [
      "ACCTG 215"
    ],
    "petitionOnlyNotes": [
      "Below is information about the credit requirements for the Bachelor of Arts in Business Administration (BABA) degree from the Foster School. Meet with an academic adviser in the Undergraduate Program Office to clarify your educational and career goals and make long-range plans to achieve them once you have been accepted to the Foster School."
    ],
    "aliases": [
      "uw-seattle-business-administration-there-is-no-need-to-submit-foster-courses-all-approved-courses-are-listed-on-the-business-minor-website-under-curriculum"
    ],
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "Required Courses"
    ],
    "sourceEvidenceLines": [
      "Required Courses",
      "Below is information about the credit requirements for the Bachelor of Arts in Business Administration (BABA) degree from the Foster School. Meet with an academic adviser in the Undergraduate Program Office to clarify your educational and career goals and make long-range plans to achieve them once you have been accepted to the Foster School.",
      "ACCTG 215 (Financial Accounting)"
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "3c256ef768c1d775596fc2847aed4dfd39c35c0481fd0a20449813e5a4719460"
  },
  {
    "filterId": "UW_SEATTLE_DESIGN_ARTH_PREFIX_COURSES",
    "filterKey": "uw-seattle-design-arth-prefix-courses",
    "label": "Uw Seattle Design Arth Prefix Courses",
    "ownerIds": [
      "uw-seattle-design"
    ],
    "campusId": "uw-seattle",
    "officialSourceUrl": "https://www.washington.edu/students/gencat/program/S/Art+ArtHistory+Design-105.html",
    "sourceUrl": "https://www.washington.edu/students/gencat/program/S/Art+ArtHistory+Design-105.html",
    "sourceRole": "official-catalog",
    "approvedUwCourseCodes": [
      "ARTH 200",
      "ARTH 201",
      "ARTH 202",
      "ARTH 203",
      "ARTH 204",
      "ARTH 206",
      "ARTH 209",
      "ARTH 212",
      "ARTH 214",
      "ARTH 220",
      "ARTH 233",
      "ARTH 270",
      "ARTH 272",
      "ARTH 290",
      "ARTH 309",
      "ARTH 310",
      "ARTH 311",
      "ARTH 312",
      "ARTH 314",
      "ARTH 333",
      "ARTH 361",
      "ARTH 373",
      "ARTH 380",
      "ARTH 381",
      "ARTH 390",
      "ARTH 391",
      "ARTH 400",
      "ARTH 412",
      "ARTH 413",
      "ARTH 414",
      "ARTH 419",
      "ARTH 435",
      "ARTH 471",
      "ARTH 473",
      "ARTH 484",
      "ARTH 488",
      "ARTH 491",
      "ARTH 492",
      "ARTH 494"
    ],
    "aliases": [
      "uw-seattle-design-arth-prefix-courses"
    ],
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "10 credits of ARTH prefix courses"
    ],
    "sourceEvidenceLines": [
      "10 credits of ARTH prefix courses",
      "Parsed approved course codes from https://www.washington.edu/students/gencat/program/S/Art+ArtHistory+Design-105.html."
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "a7266626f336838d6b3680d24896f2eba0bc73cbdbbf611469489e6c8b6a561d"
  },
  {
    "filterId": "UW_SEATTLE_LAW_SOCIETIES_AND_JUSTICE_LSJ_CORE_300_LEVEL_HUMAN_RIGHTS_OR_LAW_COURSES",
    "filterKey": "uw-seattle-law-societies-and-justice-lsj-core-300-level-human-rights-or-law-courses",
    "label": "Uw Seattle Law Societies And Justice Lsj Core 300 Level Human Rights Or Law Courses",
    "ownerIds": [
      "uw-seattle-law-societies-and-justice",
      "uw-seattle-law-societies-and-justice:pathway:honors-option"
    ],
    "campusId": "uw-seattle",
    "officialSourceUrl": "https://lsj.washington.edu/lsj-gold-curriculum-requirements",
    "sourceUrl": "https://lsj.washington.edu/lsj-gold-curriculum-requirements",
    "sourceRole": "primary-degree-requirements",
    "approvedUwCourseCodes": [
      "ENGL 131"
    ],
    "petitionOnlyNotes": [
      "This information is to be used for planning. Check your Degree Audit Reporting System (DARS) or meet with an adviser to ensure you have met all degree requirements."
    ],
    "aliases": [
      "uw-seattle-law-societies-and-justice-lsj-core-300-level-human-rights-or-law-courses"
    ],
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "Programs & Courses"
    ],
    "sourceEvidenceLines": [
      "Programs & Courses",
      "This information is to be used for planning. Check your Degree Audit Reporting System (DARS) or meet with an adviser to ensure you have met all degree requirements.",
      "5 credits of English Composition (with a grade of 2.00 or higher)"
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "6ffa54c452064001e8bf853bd5f36332d9aefb673e3e989453479b199451825f"
  },
  {
    "filterId": "UW_SEATTLE_LAW_SOCIETIES_AND_JUSTICE_LSJ_CORE_400_LEVEL_CAPSTONE_SEMINAR",
    "filterKey": "uw-seattle-law-societies-and-justice-lsj-core-400-level-capstone-seminar",
    "label": "Uw Seattle Law Societies And Justice Lsj Core 400 Level Capstone Seminar",
    "ownerIds": [
      "uw-seattle-law-societies-and-justice",
      "uw-seattle-law-societies-and-justice:pathway:honors-option"
    ],
    "campusId": "uw-seattle",
    "officialSourceUrl": "https://lsj.washington.edu/lsj-gold-curriculum-requirements",
    "sourceUrl": "https://lsj.washington.edu/lsj-gold-curriculum-requirements",
    "sourceRole": "primary-degree-requirements",
    "approvedUwCourseCodes": [
      "ENGL 131"
    ],
    "petitionOnlyNotes": [
      "This information is to be used for planning. Check your Degree Audit Reporting System (DARS) or meet with an adviser to ensure you have met all degree requirements."
    ],
    "aliases": [
      "uw-seattle-law-societies-and-justice-lsj-core-400-level-capstone-seminar"
    ],
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "Programs & Courses"
    ],
    "sourceEvidenceLines": [
      "Programs & Courses",
      "This information is to be used for planning. Check your Degree Audit Reporting System (DARS) or meet with an adviser to ensure you have met all degree requirements.",
      "5 credits of English Composition (with a grade of 2.00 or higher)"
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "21cb3f0a2be9a197cdd0fc294ea2452144bac234f83bbe2f2f0f6121d65586fe"
  },
  {
    "filterId": "UW_SEATTLE_LAW_SOCIETIES_AND_JUSTICE_REQUIRED_LSJ_300_LEVEL_COURSES",
    "filterKey": "uw-seattle-law-societies-and-justice-required-lsj-300-level-courses",
    "label": "Uw Seattle Law Societies And Justice Required Lsj 300 Level Courses",
    "ownerIds": [
      "uw-seattle-law-societies-and-justice",
      "uw-seattle-law-societies-and-justice:pathway:honors-option"
    ],
    "campusId": "uw-seattle",
    "officialSourceUrl": "https://lsj.washington.edu/lsj-gold-curriculum-requirements",
    "sourceUrl": "https://lsj.washington.edu/lsj-gold-curriculum-requirements",
    "sourceRole": "primary-degree-requirements",
    "approvedUwCourseCodes": [
      "ENGL 131"
    ],
    "petitionOnlyNotes": [
      "This information is to be used for planning. Check your Degree Audit Reporting System (DARS) or meet with an adviser to ensure you have met all degree requirements."
    ],
    "aliases": [
      "uw-seattle-law-societies-and-justice-required-lsj-300-level-courses"
    ],
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "Programs & Courses"
    ],
    "sourceEvidenceLines": [
      "Programs & Courses",
      "This information is to be used for planning. Check your Degree Audit Reporting System (DARS) or meet with an adviser to ensure you have met all degree requirements.",
      "5 credits of English Composition (with a grade of 2.00 or higher)"
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "7073be71685fd47974c5e3c8fc9392afb271c9fe8d70978ec4019c7d67183b4f"
  },
  {
    "filterId": "UW_SEATTLE_LAW_SOCIETIES_AND_JUSTICE_UPPER_DIVISION_300_AND_400_LEVEL_ELECTIVES",
    "filterKey": "uw-seattle-law-societies-and-justice-upper-division-300-and-400-level-electives",
    "label": "Uw Seattle Law Societies And Justice Upper Division 300 And 400 Level Electives",
    "ownerIds": [
      "uw-seattle-law-societies-and-justice",
      "uw-seattle-law-societies-and-justice:pathway:honors-option"
    ],
    "campusId": "uw-seattle",
    "officialSourceUrl": "https://lsj.washington.edu/lsj-gold-curriculum-requirements",
    "sourceUrl": "https://lsj.washington.edu/lsj-gold-curriculum-requirements",
    "sourceRole": "primary-degree-requirements",
    "approvedUwCourseCodes": [
      "ANTH 323",
      "DISST 346",
      "JSISA 324",
      "JSISB 326",
      "JSISB 346",
      "JSISB 366",
      "LSJ 300",
      "LSJ 320",
      "LSJ 321",
      "LSJ 322",
      "LSJ 323",
      "LSJ 324",
      "LSJ 326",
      "LSJ 327",
      "LSJ 329",
      "LSJ 345",
      "LSJ 360",
      "LSJ 361",
      "LSJ 363",
      "LSJ 366",
      "LSJ 367",
      "LSJ 368",
      "LSJ 372",
      "LSJ 375",
      "POLS 327",
      "POLS 360",
      "POLS 361",
      "POLS 363",
      "POLS 367",
      "POLS 368",
      "SOC 372"
    ],
    "approvedUwCourseGroups": [
      [
        "LSJ 320",
        "LSJ 368",
        "POLS 368"
      ],
      [
        "ANTH 323",
        "LSJ 321",
        "LSJ 323"
      ],
      [
        "JSISA 324",
        "LSJ 322",
        "LSJ 324"
      ],
      [
        "JSISB 326",
        "LSJ 326"
      ],
      [
        "LSJ 327",
        "POLS 327"
      ],
      [
        "DISST 346",
        "JSISB 346"
      ],
      [
        "LSJ 360",
        "POLS 360"
      ],
      [
        "LSJ 361",
        "POLS 361"
      ],
      [
        "LSJ 363",
        "POLS 363"
      ],
      [
        "JSISB 366",
        "LSJ 366"
      ],
      [
        "LSJ 367",
        "POLS 367"
      ],
      [
        "LSJ 372",
        "LSJ 375",
        "SOC 372"
      ]
    ],
    "aliases": [
      "uw-seattle-law-societies-and-justice-upper-division-300-and-400-level-electives"
    ],
    "generatedFromOfficialSupportSource": true,
    "sourceEvidenceHeadings": [
      "Some of these courses can alternatively be used for completion of the 300-level or electives sections, but the student will need to choose whether to use as a core, 300-level, or elective. They cannot work towards multiple requirements simultaneously."
    ],
    "sourceEvidenceLines": [
      "Some of these courses can alternatively be used for completion of the 300-level or electives sections, but the student will need to choose whether to use as a core, 300-level, or elective. They cannot work towards multiple requirements simultaneously.",
      "LSJ 300 Race, Law, and Justice (5)",
      "LSJ 320/POL S 368 The Politics and Law of International Human Rights (5)",
      "LSJ 321/ANTH 323 Human Rights Law in Culture and Practice (5)",
      "LSJ 322/JSIS A 324 Human Rights in Latin America (5)",
      "JSIS B/LSJ 326 Migrant Justice (5)",
      "LSJ/POL S 327 Women’s Rights as Human Rights (5)",
      "LSJ 329 Immigration, Citizenship, and Rights (5)",
      "LSJ 345 Environmental Justice in the Americas (5)",
      "LSJ/JSIS B/DIS ST 346 Disability in Global and Comparative Perspective (5)",
      "LSJ/POL S 360 Introduction to United States Constitutional Law (5)",
      "LSJ/POL S 361 United States Courts and Civil Liberty (5)",
      "LSJ/POL S 363 Law in Society (5)",
      "LSJ/JSIS B 366 Comparative Law and Legal Cultures (5)",
      "LSJ/POL S 367 Comparative Law and Courts (5)",
      "LSJ 375/SOC 372 Crime, Politics, and Justice (5)"
    ],
    "generatedAt": "2026-05-18T10:26:56.093Z",
    "sourceFingerprint": "140eb1cbeb98c02dc9d2bc549079a15c152347516c5330f9c6977344fe1db893"
  }
] as const;
