/* eslint-disable */
/* auto-generated by scripts/planner/parse-transfer-planner-requirement-sources.cjs */

import type {
  TransferPlannerParsedRequirementSourceBlock,
  TransferPlannerRequirementSourceAdapterSummary,
} from "./schema";

const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_0 } = require("./requirement-source-adapters.generated/blocks-000.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_1 } = require("./requirement-source-adapters.generated/blocks-001.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_2 } = require("./requirement-source-adapters.generated/blocks-002.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_3 } = require("./requirement-source-adapters.generated/blocks-003.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_4 } = require("./requirement-source-adapters.generated/blocks-004.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_5 } = require("./requirement-source-adapters.generated/blocks-005.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_6 } = require("./requirement-source-adapters.generated/blocks-006.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_7 } = require("./requirement-source-adapters.generated/blocks-007.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_8 } = require("./requirement-source-adapters.generated/blocks-008.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_9 } = require("./requirement-source-adapters.generated/blocks-009.generated.ts");

export const TRANSFER_PLANNER_REQUIREMENT_SOURCE_ADAPTER_SUMMARY = {
  "generatedAt": "2026-05-20T08:39:53.872Z",
  "totalOwners": 391,
  "okCount": 388,
  "failedCount": 3,
  "parsedRequirementSourceBlockCount": 391,
  "parsedRequirementAtomCandidateCount": 8760,
  "parsedDegreeMapBlockCandidateCount": 921,
  "parsedRequirementGroupCount": 2176,
  "parsedRequirementCourseCount": 9853,
  "snapshotFallbackCount": 196,
  "countsByAdapterId": {
    "uw-seattle-html-degree-page": 146,
    "uw-bothell-html-degree-page": 65,
    "generic-official-html-page": 41,
    "uw-seattle-catalog-page": 70,
    "generic-official-pdf-degree-sheet": 19,
    "uw-tacoma-html-degree-page": 44,
    "uw-bothell-pdf-worksheet": 3,
    "uw-tacoma-catalog-page": 3
  },
  "countsByAdapterFamily": {
    "UW Seattle HTML degree pages": 146,
    "UW Bothell HTML degree pages": 65,
    "Generic official HTML pages": 41,
    "UW Seattle catalog pages": 70,
    "Generic official PDF degree sheets": 19,
    "UW Tacoma HTML degree pages": 44,
    "UW Bothell PDF worksheets": 3,
    "UW Tacoma catalog pages": 3
  },
  "countsByCampus": {
    "uw-seattle": 268,
    "uw-bothell": 70,
    "uw-tacoma": 53
  },
  "countsByResolutionStrategy": {
    "cached-snapshot": 199,
    "primary-source": 182,
    "alternate-official-source": 10
  },
  "countsBySourceRole": {
    "primary-degree-requirements": 269,
    "department-requirements": 39,
    "official-catalog": 73,
    "non-schedulable-course-list": 3,
    "approved-course-list": 3,
    "pathway-degree-sheet": 1,
    "admission-prerequisite-source": 2,
    "elective-list": 1
  },
  "countsBySourceRoleStatus": {
    "primary": 382,
    "non-schedulable": 3,
    "support": 6
  },
  "canCreateSchedulableRowCount": 382,
  "canCreateRequiredRowCount": 382,
  "canCreateOptionGroupCount": 382,
  "canCreateApprovedFilterCount": 3,
  "canCreateElectiveListCount": 1,
  "supportOnlySourceCount": 6,
  "nonSchedulableSourceCount": 3,
  "qualityWarningCount": 179,
  "qualityNoteCount": 322,
  "countsByQualitySignalCode": {
    "snapshot-fallback-used": 196,
    "material-source-structured-drift": 57,
    "large-structured-only-course-gap": 51,
    "alternate-official-source-used": 10,
    "no-parsed-uw-course-codes": 33,
    "high-confidence-low-course-coverage": 10,
    "snapshot-fallback-heading-context-missing": 116,
    "low-confidence-parsed-source": 27,
    "uw-mse-expected-course-option-missing": 1
  }
} as TransferPlannerRequirementSourceAdapterSummary;

const TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCKS_RAW: unknown[] = ([] as unknown[]).concat(
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_0,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_1,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_2,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_3,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_4,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_5,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_6,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_7,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_8,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_9
);

export const TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCKS =
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCKS_RAW as TransferPlannerParsedRequirementSourceBlock[];

