/* eslint-disable */
/* auto-generated by scripts/planner/parse-transfer-planner-requirement-sources.cjs */

import type {
  TransferPlannerParsedRequirementSourceBlock,
  TransferPlannerRequirementSourceAdapterSummary,
} from "./schema";

const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_0 } = require("./requirement-source-adapters.generated/blocks-000.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_1 } = require("./requirement-source-adapters.generated/blocks-001.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_2 } = require("./requirement-source-adapters.generated/blocks-002.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_3 } = require("./requirement-source-adapters.generated/blocks-003.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_4 } = require("./requirement-source-adapters.generated/blocks-004.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_5 } = require("./requirement-source-adapters.generated/blocks-005.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_6 } = require("./requirement-source-adapters.generated/blocks-006.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_7 } = require("./requirement-source-adapters.generated/blocks-007.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_8 } = require("./requirement-source-adapters.generated/blocks-008.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_9 } = require("./requirement-source-adapters.generated/blocks-009.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_10 } = require("./requirement-source-adapters.generated/blocks-010.generated.ts");
const { TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_11 } = require("./requirement-source-adapters.generated/blocks-011.generated.ts");

export const TRANSFER_PLANNER_REQUIREMENT_SOURCE_ADAPTER_SUMMARY = {
  "generatedAt": "2026-05-13T02:54:36.962Z",
  "totalOwners": 456,
  "okCount": 456,
  "failedCount": 0,
  "parsedRequirementSourceBlockCount": 456,
  "parsedRequirementAtomCandidateCount": 10494,
  "parsedDegreeMapBlockCandidateCount": 615,
  "parsedRequirementGroupCount": 2314,
  "parsedRequirementCourseCount": 10405,
  "snapshotFallbackCount": 13,
  "countsByAdapterId": {
    "uw-seattle-html-degree-page": 127,
    "uw-bothell-html-degree-page": 76,
    "generic-official-html-page": 59,
    "generic-official-pdf-degree-sheet": 23,
    "uw-seattle-catalog-page": 107,
    "uw-tacoma-html-degree-page": 49,
    "uw-bothell-pdf-worksheet": 3,
    "uw-tacoma-catalog-page": 12
  },
  "countsByAdapterFamily": {
    "UW Seattle HTML degree pages": 127,
    "UW Bothell HTML degree pages": 76,
    "Generic official HTML pages": 59,
    "Generic official PDF degree sheets": 23,
    "UW Seattle catalog pages": 107,
    "UW Tacoma HTML degree pages": 49,
    "UW Bothell PDF worksheets": 3,
    "UW Tacoma catalog pages": 12
  },
  "countsByCampus": {
    "uw-seattle": 295,
    "uw-bothell": 81,
    "uw-tacoma": 80
  },
  "countsByResolutionStrategy": {
    "primary-source": 437,
    "cached-snapshot": 13,
    "alternate-official-source": 6
  },
  "countsBySourceRole": {
    "primary-degree-requirements": 294,
    "department-requirements": 37,
    "official-catalog": 120,
    "non-schedulable-course-list": 1,
    "approved-course-list": 3,
    "pathway-degree-sheet": 1
  },
  "countsBySourceRoleStatus": {
    "primary": 452,
    "non-schedulable": 1,
    "support": 3
  },
  "canCreateSchedulableRowCount": 452,
  "canCreateRequiredRowCount": 452,
  "canCreateOptionGroupCount": 452,
  "canCreateApprovedFilterCount": 3,
  "canCreateElectiveListCount": 0,
  "supportOnlySourceCount": 3,
  "nonSchedulableSourceCount": 1,
  "qualityWarningCount": 101,
  "qualityNoteCount": 19,
  "countsByQualitySignalCode": {
    "material-source-structured-drift": 43,
    "large-structured-only-course-gap": 30,
    "high-confidence-low-course-coverage": 20,
    "no-parsed-uw-course-codes": 7,
    "low-confidence-parsed-source": 1,
    "snapshot-fallback-used": 13,
    "alternate-official-source-used": 6
  }
} as TransferPlannerRequirementSourceAdapterSummary;

const TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCKS_RAW: unknown[] = ([] as unknown[]).concat(
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_0,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_1,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_2,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_3,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_4,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_5,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_6,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_7,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_8,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_9,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_10,
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCK_CHUNK_11
);

export const TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCKS =
  TRANSFER_PLANNER_PARSED_REQUIREMENT_SOURCE_BLOCKS_RAW as TransferPlannerParsedRequirementSourceBlock[];

