import type { TransferPlannerSourceGapEntry } from "./schema";

// Generated by scripts/planner/build-transfer-planner-source-gap-report.cjs
export const TRANSFER_PLANNER_SOURCE_GAP_ENTRIES: TransferPlannerSourceGapEntry[] = [
  {
    "ownerType": "major",
    "ownerKey": "uw-bothell-chemistry-biochemistry",
    "planId": "uw-bothell-chemistry-biochemistry",
    "pathwayId": null,
    "title": "Chemistry: Biochemistry (BS)",
    "campusId": "uw-bothell",
    "sourceCoverageStatus": "source-unfindable",
    "reviewStatus": "needs-source-automation",
    "studentVisibility": "hidden",
    "sourceGapReason": "No official primary degree-requirements source candidate met the minimum discovery threshold.",
    "generatedAt": "2026-05-21T15:57:04.779Z",
    "officialLinkCount": 0,
    "candidateCount": 0,
    "suggestedPrimary": null,
    "sourceDiscoveryAttempts": []
  }
];
