import type { TransferPlannerSourceGapEntry } from "./schema";

// Generated by scripts/planner/build-transfer-planner-source-gap-report.cjs
export const TRANSFER_PLANNER_SOURCE_GAP_ENTRIES: TransferPlannerSourceGapEntry[] = [
  {
    "ownerType": "pathway",
    "ownerKey": "uw-tacoma-computer-engineering:pathway:bioinformatics-option",
    "planId": "uw-tacoma-computer-engineering",
    "pathwayId": "bioinformatics-option",
    "title": "Computer Engineering - Bioinformatics Option",
    "campusId": "uw-tacoma",
    "sourceCoverageStatus": "parser-unsupported",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official source candidate found below the auto-promotion threshold; keep hidden until source discovery or a parser adapter can verify it.",
    "generatedAt": "2026-05-12T22:55:17.457Z",
    "officialLinkCount": 2,
    "candidateCount": 2,
    "suggestedPrimary": {
      "url": "https://www.washington.edu/students/gencat/program/T/SchoolofEngineeringandTechnology-1023.html",
      "label": "UW Tacoma SET catalog page",
      "score": 23,
      "confidence": "medium",
      "reasons": [
        "already stored as an official source",
        "does not clearly mention the selected major",
        "official UW General Catalog program page",
        "stays on an official UW domain"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.washington.edu/students/gencat/program/T/SchoolofEngineeringandTechnology-1023.html",
        "label": "UW Tacoma SET catalog page",
        "score": 23,
        "confidence": "medium",
        "reasons": [
          "already stored as an official source",
          "does not clearly mention the selected major",
          "official UW General Catalog program page",
          "stays on an official UW domain"
        ]
      },
      {
        "url": "https://admit.washington.edu/apply/transfer/equivalency-guide/green-river/",
        "label": "UW Green River transfer equivalency guide",
        "score": -89,
        "confidence": "low",
        "reasons": [
          "admissions wording",
          "already stored as an official source",
          "does not clearly mention the selected major",
          "stays on an official UW domain",
          "transfer equivalency is not degree-requirement authority",
          "transfer-equivalency wording"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-tacoma-computer-engineering:pathway:cybersecurity-option",
    "planId": "uw-tacoma-computer-engineering",
    "pathwayId": "cybersecurity-option",
    "title": "Computer Engineering - Cybersecurity Option",
    "campusId": "uw-tacoma",
    "sourceCoverageStatus": "parser-unsupported",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official source candidate found below the auto-promotion threshold; keep hidden until source discovery or a parser adapter can verify it.",
    "generatedAt": "2026-05-12T22:55:17.457Z",
    "officialLinkCount": 2,
    "candidateCount": 2,
    "suggestedPrimary": {
      "url": "https://www.washington.edu/students/gencat/program/T/SchoolofEngineeringandTechnology-1023.html",
      "label": "UW Tacoma SET catalog page",
      "score": 23,
      "confidence": "medium",
      "reasons": [
        "already stored as an official source",
        "does not clearly mention the selected major",
        "official UW General Catalog program page",
        "stays on an official UW domain"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.washington.edu/students/gencat/program/T/SchoolofEngineeringandTechnology-1023.html",
        "label": "UW Tacoma SET catalog page",
        "score": 23,
        "confidence": "medium",
        "reasons": [
          "already stored as an official source",
          "does not clearly mention the selected major",
          "official UW General Catalog program page",
          "stays on an official UW domain"
        ]
      },
      {
        "url": "https://admit.washington.edu/apply/transfer/equivalency-guide/green-river/",
        "label": "UW Green River transfer equivalency guide",
        "score": -89,
        "confidence": "low",
        "reasons": [
          "admissions wording",
          "already stored as an official source",
          "does not clearly mention the selected major",
          "stays on an official UW domain",
          "transfer equivalency is not degree-requirement authority",
          "transfer-equivalency wording"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-tacoma-electrical-engineering:pathway:bioinformatics-option",
    "planId": "uw-tacoma-electrical-engineering",
    "pathwayId": "bioinformatics-option",
    "title": "Electrical Engineering - Bioinformatics Option",
    "campusId": "uw-tacoma",
    "sourceCoverageStatus": "parser-unsupported",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official source candidate found below the auto-promotion threshold; keep hidden until source discovery or a parser adapter can verify it.",
    "generatedAt": "2026-05-12T22:55:17.457Z",
    "officialLinkCount": 2,
    "candidateCount": 2,
    "suggestedPrimary": {
      "url": "https://www.washington.edu/students/gencat/program/T/SchoolofEngineeringandTechnology-1023.html",
      "label": "UW Tacoma SET catalog page",
      "score": 23,
      "confidence": "medium",
      "reasons": [
        "already stored as an official source",
        "does not clearly mention the selected major",
        "official UW General Catalog program page",
        "stays on an official UW domain"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.washington.edu/students/gencat/program/T/SchoolofEngineeringandTechnology-1023.html",
        "label": "UW Tacoma SET catalog page",
        "score": 23,
        "confidence": "medium",
        "reasons": [
          "already stored as an official source",
          "does not clearly mention the selected major",
          "official UW General Catalog program page",
          "stays on an official UW domain"
        ]
      },
      {
        "url": "https://admit.washington.edu/apply/transfer/equivalency-guide/green-river/",
        "label": "UW Green River transfer equivalency guide",
        "score": -89,
        "confidence": "low",
        "reasons": [
          "admissions wording",
          "already stored as an official source",
          "does not clearly mention the selected major",
          "stays on an official UW domain",
          "transfer equivalency is not degree-requirement authority",
          "transfer-equivalency wording"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-tacoma-electrical-engineering:pathway:cybersecurity-option",
    "planId": "uw-tacoma-electrical-engineering",
    "pathwayId": "cybersecurity-option",
    "title": "Electrical Engineering - Cybersecurity Option",
    "campusId": "uw-tacoma",
    "sourceCoverageStatus": "parser-unsupported",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official source candidate found below the auto-promotion threshold; keep hidden until source discovery or a parser adapter can verify it.",
    "generatedAt": "2026-05-12T22:55:17.457Z",
    "officialLinkCount": 2,
    "candidateCount": 2,
    "suggestedPrimary": {
      "url": "https://www.washington.edu/students/gencat/program/T/SchoolofEngineeringandTechnology-1023.html",
      "label": "UW Tacoma SET catalog page",
      "score": 23,
      "confidence": "medium",
      "reasons": [
        "already stored as an official source",
        "does not clearly mention the selected major",
        "official UW General Catalog program page",
        "stays on an official UW domain"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.washington.edu/students/gencat/program/T/SchoolofEngineeringandTechnology-1023.html",
        "label": "UW Tacoma SET catalog page",
        "score": 23,
        "confidence": "medium",
        "reasons": [
          "already stored as an official source",
          "does not clearly mention the selected major",
          "official UW General Catalog program page",
          "stays on an official UW domain"
        ]
      },
      {
        "url": "https://admit.washington.edu/apply/transfer/equivalency-guide/green-river/",
        "label": "UW Green River transfer equivalency guide",
        "score": -89,
        "confidence": "low",
        "reasons": [
          "admissions wording",
          "already stored as an official source",
          "does not clearly mention the selected major",
          "stays on an official UW domain",
          "transfer equivalency is not degree-requirement authority",
          "transfer-equivalency wording"
        ]
      }
    ]
  }
];
