import type { TransferPlannerSourceGapEntry } from "./schema";

// Generated by scripts/planner/build-transfer-planner-source-gap-report.cjs
export const TRANSFER_PLANNER_SOURCE_GAP_ENTRIES: TransferPlannerSourceGapEntry[] = [
  {
    "ownerType": "major",
    "ownerKey": "uw-bothell-business-administration-accounting",
    "planId": "uw-bothell-business-administration-accounting",
    "pathwayId": null,
    "title": "Business Administration: Accounting (BA)",
    "campusId": "uw-bothell",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "high-confidence-needs-review",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is high confidence but still requires human/source-pipeline review before student visibility.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 138,
    "suggestedPrimary": {
      "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/accounting",
      "label": "Accounting Option",
      "score": 85,
      "confidence": "high",
      "reasons": [
        "already stored as an official source",
        "department requirements source role",
        "matches major keyword \"accounting\"",
        "matches major keyword \"administration\"",
        "matches major keyword \"business\"",
        "matches multiple major keywords",
        "official source text matches the selected major",
        "stays on an official UW domain",
        "undergraduate path segment",
        "verified against an official source candidate"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/accounting",
        "label": "Accounting Option",
        "score": 85,
        "confidence": "high",
        "reasons": [
          "already stored as an official source",
          "department requirements source role",
          "matches major keyword \"accounting\"",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches multiple major keywords",
          "official source text matches the selected major",
          "stays on an official UW domain",
          "undergraduate path segment",
          "verified against an official source candidate"
        ]
      },
      {
        "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/accounting#content",
        "label": "Skip To Content",
        "score": 81,
        "confidence": "high",
        "reasons": [
          "department requirements source role",
          "discovered from an official source page",
          "matches major keyword \"accounting\"",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches multiple major keywords",
          "official source text matches the selected major",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      },
      {
        "url": "https://www.uwb.edu/business/undergraduate/business-administration/accounting",
        "label": "Accounting",
        "score": 81,
        "confidence": "high",
        "reasons": [
          "department requirements source role",
          "discovered from an official source page",
          "matches major keyword \"accounting\"",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches multiple major keywords",
          "official source path matches the selected major",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      }
    ]
  },
  {
    "ownerType": "major",
    "ownerKey": "uw-bothell-business-administration-finance",
    "planId": "uw-bothell-business-administration-finance",
    "pathwayId": null,
    "title": "Business Administration: Finance (BA)",
    "campusId": "uw-bothell",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "high-confidence-needs-review",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is high confidence but still requires human/source-pipeline review before student visibility.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 138,
    "suggestedPrimary": {
      "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/finance-option",
      "label": "Finance Option and Concentration",
      "score": 85,
      "confidence": "high",
      "reasons": [
        "already stored as an official source",
        "department requirements source role",
        "matches major keyword \"administration\"",
        "matches major keyword \"business\"",
        "matches major keyword \"finance\"",
        "matches multiple major keywords",
        "official source text matches the selected major",
        "stays on an official UW domain",
        "undergraduate path segment",
        "verified against an official source candidate"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/finance-option",
        "label": "Finance Option and Concentration",
        "score": 85,
        "confidence": "high",
        "reasons": [
          "already stored as an official source",
          "department requirements source role",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches major keyword \"finance\"",
          "matches multiple major keywords",
          "official source text matches the selected major",
          "stays on an official UW domain",
          "undergraduate path segment",
          "verified against an official source candidate"
        ]
      },
      {
        "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/finance-option#content",
        "label": "Skip To Content",
        "score": 81,
        "confidence": "high",
        "reasons": [
          "department requirements source role",
          "discovered from an official source page",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches major keyword \"finance\"",
          "matches multiple major keywords",
          "official source text matches the selected major",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      },
      {
        "url": "https://www.uwb.edu/business/undergraduate/business-administration/finance",
        "label": "Finance",
        "score": 81,
        "confidence": "high",
        "reasons": [
          "department requirements source role",
          "discovered from an official source page",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches major keyword \"finance\"",
          "matches multiple major keywords",
          "official source path matches the selected major",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      }
    ]
  },
  {
    "ownerType": "major",
    "ownerKey": "uw-bothell-business-administration-leadership-and-strategic-innovation",
    "planId": "uw-bothell-business-administration-leadership-and-strategic-innovation",
    "pathwayId": null,
    "title": "Business Administration: Leadership & Strategic Innovation (BA)",
    "campusId": "uw-bothell",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "high-confidence-needs-review",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is high confidence but still requires human/source-pipeline review before student visibility.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 138,
    "suggestedPrimary": {
      "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/leadership",
      "label": "Leadership & Strategic Innovation Option",
      "score": 89,
      "confidence": "high",
      "reasons": [
        "already stored as an official source",
        "department requirements source role",
        "matches major keyword \"administration\"",
        "matches major keyword \"business\"",
        "matches major keyword \"innovation\"",
        "matches major keyword \"leadership\"",
        "matches major keyword \"strategic\"",
        "matches multiple major keywords",
        "official source text matches the selected major",
        "stays on an official UW domain",
        "undergraduate path segment",
        "verified against an official source candidate"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/leadership",
        "label": "Leadership & Strategic Innovation Option",
        "score": 89,
        "confidence": "high",
        "reasons": [
          "already stored as an official source",
          "department requirements source role",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches major keyword \"innovation\"",
          "matches major keyword \"leadership\"",
          "matches major keyword \"strategic\"",
          "matches multiple major keywords",
          "official source text matches the selected major",
          "stays on an official UW domain",
          "undergraduate path segment",
          "verified against an official source candidate"
        ]
      },
      {
        "url": "https://www.uwb.edu/business/undergraduate/business-administration/leadership",
        "label": "Leadership & Strategic Innovation",
        "score": 85,
        "confidence": "high",
        "reasons": [
          "department requirements source role",
          "discovered from an official source page",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches major keyword \"innovation\"",
          "matches major keyword \"leadership\"",
          "matches major keyword \"strategic\"",
          "matches multiple major keywords",
          "official source text matches the selected major",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      },
      {
        "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/leadership#content",
        "label": "Skip To Content",
        "score": 66,
        "confidence": "high",
        "reasons": [
          "admissions or preparation source role",
          "curriculum wording",
          "discovered from an official source page",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches major keyword \"innovation\"",
          "matches major keyword \"leadership\"",
          "matches major keyword \"strategic\"",
          "matches multiple major keywords",
          "non-degree content wording",
          "official source text matches the selected major",
          "page title fetched successfully",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      }
    ]
  },
  {
    "ownerType": "major",
    "ownerKey": "uw-bothell-business-administration-marketing",
    "planId": "uw-bothell-business-administration-marketing",
    "pathwayId": null,
    "title": "Business Administration: Marketing (BA)",
    "campusId": "uw-bothell",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "high-confidence-needs-review",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is high confidence but still requires human/source-pipeline review before student visibility.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 138,
    "suggestedPrimary": {
      "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/marketing",
      "label": "Marketing Option and Concentration",
      "score": 85,
      "confidence": "high",
      "reasons": [
        "already stored as an official source",
        "department requirements source role",
        "matches major keyword \"administration\"",
        "matches major keyword \"business\"",
        "matches major keyword \"marketing\"",
        "matches multiple major keywords",
        "official source text matches the selected major",
        "stays on an official UW domain",
        "undergraduate path segment",
        "verified against an official source candidate"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/marketing",
        "label": "Marketing Option and Concentration",
        "score": 85,
        "confidence": "high",
        "reasons": [
          "already stored as an official source",
          "department requirements source role",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches major keyword \"marketing\"",
          "matches multiple major keywords",
          "official source text matches the selected major",
          "stays on an official UW domain",
          "undergraduate path segment",
          "verified against an official source candidate"
        ]
      },
      {
        "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/marketing#content",
        "label": "Skip To Content",
        "score": 81,
        "confidence": "high",
        "reasons": [
          "department requirements source role",
          "discovered from an official source page",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches major keyword \"marketing\"",
          "matches multiple major keywords",
          "official source text matches the selected major",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      },
      {
        "url": "https://www.uwb.edu/business/undergraduate/business-administration/marketing",
        "label": "Marketing",
        "score": 81,
        "confidence": "high",
        "reasons": [
          "department requirements source role",
          "discovered from an official source page",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches major keyword \"marketing\"",
          "matches multiple major keywords",
          "official source path matches the selected major",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      }
    ]
  },
  {
    "ownerType": "major",
    "ownerKey": "uw-bothell-business-administration-supply-chain-management",
    "planId": "uw-bothell-business-administration-supply-chain-management",
    "pathwayId": null,
    "title": "Business Administration: Supply Chain Management (BA)",
    "campusId": "uw-bothell",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "high-confidence-needs-review",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is high confidence but still requires human/source-pipeline review before student visibility.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 138,
    "suggestedPrimary": {
      "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/supply-chain",
      "label": "Supply Chain Management Option",
      "score": 89,
      "confidence": "high",
      "reasons": [
        "already stored as an official source",
        "department requirements source role",
        "matches major keyword \"administration\"",
        "matches major keyword \"business\"",
        "matches major keyword \"chain\"",
        "matches major keyword \"management\"",
        "matches major keyword \"supply\"",
        "matches multiple major keywords",
        "official source text matches the selected major",
        "stays on an official UW domain",
        "undergraduate path segment",
        "verified against an official source candidate"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/supply-chain",
        "label": "Supply Chain Management Option",
        "score": 89,
        "confidence": "high",
        "reasons": [
          "already stored as an official source",
          "department requirements source role",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches major keyword \"chain\"",
          "matches major keyword \"management\"",
          "matches major keyword \"supply\"",
          "matches multiple major keywords",
          "official source text matches the selected major",
          "stays on an official UW domain",
          "undergraduate path segment",
          "verified against an official source candidate"
        ]
      },
      {
        "url": "https://www.uwb.edu/business/undergraduate/business-administration/supply-chain",
        "label": "Supply Chain Management",
        "score": 85,
        "confidence": "high",
        "reasons": [
          "department requirements source role",
          "discovered from an official source page",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches major keyword \"chain\"",
          "matches major keyword \"management\"",
          "matches major keyword \"supply\"",
          "matches multiple major keywords",
          "official source text matches the selected major",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      },
      {
        "url": "https://www.uwb.edu/business/undergraduate/bachelor-of-business-administration/supply-chain#content",
        "label": "Skip To Content",
        "score": 64,
        "confidence": "high",
        "reasons": [
          "admissions or preparation source role",
          "curriculum wording",
          "discovered from an official source page",
          "matches major keyword \"administration\"",
          "matches major keyword \"business\"",
          "matches major keyword \"chain\"",
          "matches major keyword \"management\"",
          "matches major keyword \"supply\"",
          "matches multiple major keywords",
          "matches the selected degree route",
          "non-degree content wording",
          "official source text matches the selected major",
          "page title fetched successfully",
          "route-specific page may not cover every pathway in the selected major",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      }
    ]
  },
  {
    "ownerType": "major",
    "ownerKey": "uw-bothell-chemistry-bs",
    "planId": "uw-bothell-chemistry-bs",
    "pathwayId": null,
    "title": "Chemistry (BS)",
    "campusId": "uw-bothell",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "high-confidence-needs-review",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is high confidence but still requires human/source-pipeline review before student visibility.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 225,
    "suggestedPrimary": {
      "url": "https://www.uwb.edu/stem/undergraduate/majors/chemistry/resources#content",
      "label": "Skip To Content",
      "score": 73,
      "confidence": "high",
      "reasons": [
        "department requirements source role",
        "discovered from an official source page",
        "matches major keyword \"chemistry\"",
        "official source path matches the selected major",
        "stays on an official UW domain",
        "stays on the same department or school page",
        "undergraduate path segment"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.uwb.edu/stem/undergraduate/majors/chemistry/curriculum",
        "label": "Scoped section: B.S. in Chemistry (general option) requirements",
        "score": 79,
        "confidence": "high",
        "reasons": [
          "already stored as an official source",
          "curriculum map source role",
          "curriculum wording",
          "matches major keyword \"chemistry\"",
          "matches the selected degree route",
          "official source path matches the selected major",
          "route-specific page may not cover every pathway in the selected major",
          "stays on an official UW domain",
          "undergraduate path segment",
          "verified against an official source candidate"
        ]
      },
      {
        "url": "https://www.uwb.edu/stem/undergraduate/majors/chemistry/curriculum#content",
        "label": "Skip To Content",
        "score": 77,
        "confidence": "high",
        "reasons": [
          "curriculum map source role",
          "curriculum wording",
          "discovered from an official source page",
          "matches major keyword \"chemistry\"",
          "official source path matches the selected major",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      },
      {
        "url": "https://www.uwb.edu/stem/undergraduate/majors/chemistry/curriculum#planning",
        "label": "Important planning notes",
        "score": 77,
        "confidence": "high",
        "reasons": [
          "curriculum map source role",
          "curriculum wording",
          "discovered from an official source page",
          "matches major keyword \"chemistry\"",
          "official source path matches the selected major",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-bothell-chemistry-bs:pathway:biochemistry-option",
    "planId": "uw-bothell-chemistry-bs",
    "pathwayId": "biochemistry-option",
    "title": "Chemistry (BS) - Biochemistry Option",
    "campusId": "uw-bothell",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "high-confidence-needs-review",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is high confidence but still requires human/source-pipeline review before student visibility.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 268,
    "suggestedPrimary": {
      "url": "https://www.uwb.edu/stem/undergraduate/majors/chemistry/biochemistry-option#content",
      "label": "Skip To Content",
      "score": 117,
      "confidence": "high",
      "reasons": [
        "discovered from an official source page",
        "explicitly names the selected pathway or route",
        "matches major keyword \"biochemistry\"",
        "matches major keyword \"chemistry\"",
        "matches multiple major keywords",
        "official source path matches the selected pathway",
        "pathway-specific official child page matches the selected pathway",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "stays on the same department or school page",
        "undergraduate path segment"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.uwb.edu/stem/undergraduate/majors/chemistry/biochemistry-option#content",
        "label": "Skip To Content",
        "score": 117,
        "confidence": "high",
        "reasons": [
          "discovered from an official source page",
          "explicitly names the selected pathway or route",
          "matches major keyword \"biochemistry\"",
          "matches major keyword \"chemistry\"",
          "matches multiple major keywords",
          "official source path matches the selected pathway",
          "pathway-specific official child page matches the selected pathway",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      },
      {
        "url": "https://www.uwb.edu/stem/undergraduate/majors/applied-computing/biochemistry-option#content",
        "label": "Skip To Content",
        "score": 111,
        "confidence": "high",
        "reasons": [
          "discovered from an official source page",
          "explicitly names the selected pathway or route",
          "matches major keyword \"biochemistry\"",
          "official source path matches the selected pathway",
          "pathway-specific official child page matches the selected pathway",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      },
      {
        "url": "https://www.uwb.edu/stem/undergraduate/majors/biology/biochemistry-option#content",
        "label": "Skip To Content",
        "score": 111,
        "confidence": "high",
        "reasons": [
          "discovered from an official source page",
          "explicitly names the selected pathway or route",
          "matches major keyword \"biochemistry\"",
          "official source path matches the selected pathway",
          "pathway-specific official child page matches the selected pathway",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-seattle-biology:pathway:bs-option-family:ecology-evolution-and-conservation",
    "planId": "uw-seattle-biology",
    "pathwayId": "bs-option-family:ecology-evolution-and-conservation",
    "title": "Biology - B.S. Ecology, Evolution, and Conservation option",
    "campusId": "uw-seattle",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "medium-confidence",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is below the auto-promotion threshold; keep hidden until source discovery or parser support verifies it.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 2,
    "candidateCount": 243,
    "suggestedPrimary": {
      "url": "https://admit.washington.edu/apply/running-start/",
      "label": "Running Start",
      "score": 26,
      "confidence": "medium",
      "reasons": [
        "admissions wording",
        "discovered from an official source page",
        "does not clearly mention the selected major",
        "graduation requirements wording",
        "page title fetched successfully",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-fab6faf9-550a-48ac-aa22-c8b284b5d115",
        "label": "Minor in Paleobiology",
        "score": 149,
        "confidence": "high",
        "reasons": [
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"conservation\"",
          "matches major keyword \"ecology\"",
          "matches major keyword \"evolution\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-670406500bcbc98d8a6ea187",
        "label": "Bachelor of Science degree with a major in Biology: General",
        "score": 131,
        "confidence": "high",
        "reasons": [
          "candidate appears to describe a different degree route",
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"conservation\"",
          "matches major keyword \"ecology\"",
          "matches major keyword \"evolution\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-6704083591c5178a667fb929",
        "label": "Bachelor of Science degree with a major in Biology: Plant",
        "score": 131,
        "confidence": "high",
        "reasons": [
          "candidate appears to describe a different degree route",
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"conservation\"",
          "matches major keyword \"ecology\"",
          "matches major keyword \"evolution\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-seattle-biology:pathway:bs-option-family:general-biology",
    "planId": "uw-seattle-biology",
    "pathwayId": "bs-option-family:general-biology",
    "title": "Biology - B.S. General Biology option",
    "campusId": "uw-seattle",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "medium-confidence",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is below the auto-promotion threshold; keep hidden until source discovery or parser support verifies it.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 2,
    "candidateCount": 243,
    "suggestedPrimary": {
      "url": "https://admit.washington.edu/apply/running-start/",
      "label": "Running Start",
      "score": 26,
      "confidence": "medium",
      "reasons": [
        "admissions wording",
        "discovered from an official source page",
        "does not clearly mention the selected major",
        "graduation requirements wording",
        "page title fetched successfully",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-fab6faf9-550a-48ac-aa22-c8b284b5d115",
        "label": "Minor in Paleobiology",
        "score": 145,
        "confidence": "high",
        "reasons": [
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"general\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-66fdc8be23f02d5e38e37ff0",
        "label": "Bachelor of Science degree with a major in Biology: Ecology, Evolution, and Conservation",
        "score": 127,
        "confidence": "high",
        "reasons": [
          "candidate appears to describe a different degree route",
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"general\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-6704083591c5178a667fb929",
        "label": "Bachelor of Science degree with a major in Biology: Plant",
        "score": 127,
        "confidence": "high",
        "reasons": [
          "candidate appears to describe a different degree route",
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"general\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-seattle-biology:pathway:bs-option-family:molecular-cellular-and-developmental-biology",
    "planId": "uw-seattle-biology",
    "pathwayId": "bs-option-family:molecular-cellular-and-developmental-biology",
    "title": "Biology - B.S. Molecular, Cellular, and Developmental Biology option",
    "campusId": "uw-seattle",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "medium-confidence",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is below the auto-promotion threshold; keep hidden until source discovery or parser support verifies it.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 2,
    "candidateCount": 243,
    "suggestedPrimary": {
      "url": "https://admit.washington.edu/apply/running-start/",
      "label": "Running Start",
      "score": 26,
      "confidence": "medium",
      "reasons": [
        "admissions wording",
        "discovered from an official source page",
        "does not clearly mention the selected major",
        "graduation requirements wording",
        "page title fetched successfully",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-fab6faf9-550a-48ac-aa22-c8b284b5d115",
        "label": "Minor in Paleobiology",
        "score": 147,
        "confidence": "high",
        "reasons": [
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"cellular\"",
          "matches major keyword \"molecular\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-66fdc8be23f02d5e38e37ff0",
        "label": "Bachelor of Science degree with a major in Biology: Ecology, Evolution, and Conservation",
        "score": 129,
        "confidence": "high",
        "reasons": [
          "candidate appears to describe a different degree route",
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"cellular\"",
          "matches major keyword \"molecular\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-670406500bcbc98d8a6ea187",
        "label": "Bachelor of Science degree with a major in Biology: General",
        "score": 129,
        "confidence": "high",
        "reasons": [
          "candidate appears to describe a different degree route",
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"cellular\"",
          "matches major keyword \"molecular\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-seattle-biology:pathway:bs-option-family:physiology",
    "planId": "uw-seattle-biology",
    "pathwayId": "bs-option-family:physiology",
    "title": "Biology - B.S. Physiology option",
    "campusId": "uw-seattle",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "medium-confidence",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is below the auto-promotion threshold; keep hidden until source discovery or parser support verifies it.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 2,
    "candidateCount": 243,
    "suggestedPrimary": {
      "url": "https://admit.washington.edu/apply/running-start/",
      "label": "Running Start",
      "score": 26,
      "confidence": "medium",
      "reasons": [
        "admissions wording",
        "discovered from an official source page",
        "does not clearly mention the selected major",
        "graduation requirements wording",
        "page title fetched successfully",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-fab6faf9-550a-48ac-aa22-c8b284b5d115",
        "label": "Minor in Paleobiology",
        "score": 145,
        "confidence": "high",
        "reasons": [
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"physiology\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-66fdc8be23f02d5e38e37ff0",
        "label": "Bachelor of Science degree with a major in Biology: Ecology, Evolution, and Conservation",
        "score": 127,
        "confidence": "high",
        "reasons": [
          "candidate appears to describe a different degree route",
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"physiology\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-670406500bcbc98d8a6ea187",
        "label": "Bachelor of Science degree with a major in Biology: General",
        "score": 127,
        "confidence": "high",
        "reasons": [
          "candidate appears to describe a different degree route",
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"physiology\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-seattle-biology:pathway:bs-option-family:plant-biology",
    "planId": "uw-seattle-biology",
    "pathwayId": "bs-option-family:plant-biology",
    "title": "Biology - B.S. Plant Biology option",
    "campusId": "uw-seattle",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "medium-confidence",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is below the auto-promotion threshold; keep hidden until source discovery or parser support verifies it.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 2,
    "candidateCount": 243,
    "suggestedPrimary": {
      "url": "https://admit.washington.edu/apply/running-start/",
      "label": "Running Start",
      "score": 26,
      "confidence": "medium",
      "reasons": [
        "admissions wording",
        "discovered from an official source page",
        "does not clearly mention the selected major",
        "graduation requirements wording",
        "page title fetched successfully",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-fab6faf9-550a-48ac-aa22-c8b284b5d115",
        "label": "Minor in Paleobiology",
        "score": 145,
        "confidence": "high",
        "reasons": [
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"plant\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-66fdc8be23f02d5e38e37ff0",
        "label": "Bachelor of Science degree with a major in Biology: Ecology, Evolution, and Conservation",
        "score": 127,
        "confidence": "high",
        "reasons": [
          "candidate appears to describe a different degree route",
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"plant\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-670406500bcbc98d8a6ea187",
        "label": "Bachelor of Science degree with a major in Biology: General",
        "score": 127,
        "confidence": "high",
        "reasons": [
          "candidate appears to describe a different degree route",
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"plant\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-seattle-biology:pathway:ecology-evolution-and-conservation-biology-eec-option",
    "planId": "uw-seattle-biology",
    "pathwayId": "ecology-evolution-and-conservation-biology-eec-option",
    "title": "Biology - Ecology Evolution and Conservation Biology (Eec) Option",
    "campusId": "uw-seattle",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "high-confidence-needs-review",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is high confidence but still requires human/source-pipeline review before student visibility.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 2,
    "candidateCount": 243,
    "suggestedPrimary": {
      "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-983a3f63-b310-4811-86d9-31fff47fa670",
      "label": "Bachelor of Arts degree with a major in Biology",
      "score": 149,
      "confidence": "high",
      "reasons": [
        "checklist-style wording",
        "curriculum wording",
        "discovered from an official source page",
        "explicit degree-requirements wording",
        "explicit major-requirements wording",
        "matches major keyword \"biology\"",
        "matches major keyword \"conservation\"",
        "matches major keyword \"ecology\"",
        "matches major keyword \"evolution\"",
        "matches multiple major keywords",
        "official UW General Catalog program page",
        "specific bachelor route wording",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-983a3f63-b310-4811-86d9-31fff47fa670",
        "label": "Bachelor of Arts degree with a major in Biology",
        "score": 149,
        "confidence": "high",
        "reasons": [
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"conservation\"",
          "matches major keyword \"ecology\"",
          "matches major keyword \"evolution\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-fab6faf9-550a-48ac-aa22-c8b284b5d115",
        "label": "Minor in Paleobiology",
        "score": 149,
        "confidence": "high",
        "reasons": [
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"conservation\"",
          "matches major keyword \"ecology\"",
          "matches major keyword \"evolution\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-66fdc8be23f02d5e38e37ff0",
        "label": "Bachelor of Science degree with a major in Biology: Ecology, Evolution, and Conservation",
        "score": 131,
        "confidence": "high",
        "reasons": [
          "candidate appears to describe a different degree route",
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"conservation\"",
          "matches major keyword \"ecology\"",
          "matches major keyword \"evolution\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-seattle-biology:pathway:molecular-cellular-and-developmental-biology-mcd-option",
    "planId": "uw-seattle-biology",
    "pathwayId": "molecular-cellular-and-developmental-biology-mcd-option",
    "title": "Biology - Molecular Cellular and Developmental Biology (Mcd) Option",
    "campusId": "uw-seattle",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "high-confidence-needs-review",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is high confidence but still requires human/source-pipeline review before student visibility.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 2,
    "candidateCount": 243,
    "suggestedPrimary": {
      "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-983a3f63-b310-4811-86d9-31fff47fa670",
      "label": "Bachelor of Arts degree with a major in Biology",
      "score": 147,
      "confidence": "high",
      "reasons": [
        "checklist-style wording",
        "curriculum wording",
        "discovered from an official source page",
        "explicit degree-requirements wording",
        "explicit major-requirements wording",
        "matches major keyword \"biology\"",
        "matches major keyword \"cellular\"",
        "matches major keyword \"molecular\"",
        "matches multiple major keywords",
        "official UW General Catalog program page",
        "specific bachelor route wording",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-983a3f63-b310-4811-86d9-31fff47fa670",
        "label": "Bachelor of Arts degree with a major in Biology",
        "score": 147,
        "confidence": "high",
        "reasons": [
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"cellular\"",
          "matches major keyword \"molecular\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-fab6faf9-550a-48ac-aa22-c8b284b5d115",
        "label": "Minor in Paleobiology",
        "score": 147,
        "confidence": "high",
        "reasons": [
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"cellular\"",
          "matches major keyword \"molecular\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.washington.edu/students/gencat/program/S/Biology-112.html#credential-66fdc8be23f02d5e38e37ff0",
        "label": "Bachelor of Science degree with a major in Biology: Ecology, Evolution, and Conservation",
        "score": 129,
        "confidence": "high",
        "reasons": [
          "candidate appears to describe a different degree route",
          "checklist-style wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "explicit major-requirements wording",
          "matches major keyword \"biology\"",
          "matches major keyword \"cellular\"",
          "matches major keyword \"molecular\"",
          "matches multiple major keywords",
          "official UW General Catalog program page",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "major",
    "ownerKey": "uw-seattle-english-language-literature-and-culture",
    "planId": "uw-seattle-english-language-literature-and-culture",
    "pathwayId": null,
    "title": "English - Language, Literature & Culture",
    "campusId": "uw-seattle",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "high-confidence-needs-review",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is high confidence but still requires human/source-pipeline review before student visibility.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 178,
    "suggestedPrimary": {
      "url": "https://english.washington.edu/english-language-literature-and-culture-option",
      "label": "UW English LLC option requirements",
      "score": 80,
      "confidence": "high",
      "reasons": [
        "admissions wording",
        "already stored as an official source",
        "explicit major-requirements wording",
        "matches major keyword \"english\"",
        "official source path matches the selected major",
        "page title fetched successfully",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "verified against an official source candidate"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://english.washington.edu/english-language-literature-and-culture-option",
        "label": "UW English LLC option requirements",
        "score": 80,
        "confidence": "high",
        "reasons": [
          "admissions wording",
          "already stored as an official source",
          "explicit major-requirements wording",
          "matches major keyword \"english\"",
          "official source path matches the selected major",
          "page title fetched successfully",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "verified against an official source candidate"
        ]
      },
      {
        "url": "https://english.washington.edu/language-and-literature-option-requirements-summer-2019-spring-2022#reqs",
        "label": "Major requirements",
        "score": 69,
        "confidence": "high",
        "reasons": [
          "discovered from an official source page",
          "explicit major-requirements wording",
          "matches major keyword \"english\"",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://english.washington.edu/undergraduate-programs",
        "label": "Undergraduate",
        "score": 42,
        "confidence": "high",
        "reasons": [
          "department requirements source role",
          "discovered from an official source page",
          "matches major keyword \"english\"",
          "page title fetched successfully",
          "stays on an official UW domain",
          "stays on the same department or school page",
          "undergraduate path segment"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-seattle-english-language-literature-and-culture:pathway:creative-writing-option",
    "planId": "uw-seattle-english-language-literature-and-culture",
    "pathwayId": "creative-writing-option",
    "title": "English - Language, Literature & Culture - Creative Writing Option",
    "campusId": "uw-seattle",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "high-confidence-needs-review",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is high confidence but still requires human/source-pipeline review before student visibility.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 183,
    "suggestedPrimary": {
      "url": "https://english.washington.edu/english-major-creative-writing-option",
      "label": "BA in English, Creative Writing Option",
      "score": 102,
      "confidence": "high",
      "reasons": [
        "discovered from an official source page",
        "explicitly names the selected pathway or route",
        "matches major keyword \"creative\"",
        "matches major keyword \"english\"",
        "matches major keyword \"writing\"",
        "matches multiple major keywords",
        "official source text matches the selected pathway",
        "page title fetched successfully",
        "pathway-specific official child page matches the selected pathway",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://english.washington.edu/english-major-creative-writing-option",
        "label": "BA in English, Creative Writing Option",
        "score": 102,
        "confidence": "high",
        "reasons": [
          "discovered from an official source page",
          "explicitly names the selected pathway or route",
          "matches major keyword \"creative\"",
          "matches major keyword \"english\"",
          "matches major keyword \"writing\"",
          "matches multiple major keywords",
          "official source text matches the selected pathway",
          "page title fetched successfully",
          "pathway-specific official child page matches the selected pathway",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://english.washington.edu/creative-writing-option-older-requirement-sets",
        "label": "Older Creative Writing Requirements",
        "score": 101,
        "confidence": "high",
        "reasons": [
          "discovered from an official source page",
          "explicitly names the selected pathway or route",
          "matches major keyword \"creative\"",
          "matches major keyword \"english\"",
          "matches major keyword \"writing\"",
          "matches multiple major keywords",
          "official source text matches the selected pathway",
          "pathway-specific official child page matches the selected pathway",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://english.washington.edu/english-creative-writing-option",
        "label": "Creative Writing Majors",
        "score": 101,
        "confidence": "high",
        "reasons": [
          "discovered from an official source page",
          "explicitly names the selected pathway or route",
          "matches major keyword \"creative\"",
          "matches major keyword \"english\"",
          "matches major keyword \"writing\"",
          "matches multiple major keywords",
          "official source text matches the selected pathway",
          "pathway-specific official child page matches the selected pathway",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "major",
    "ownerKey": "uw-tacoma-computer-science-and-systems-bs",
    "planId": "uw-tacoma-computer-science-and-systems-bs",
    "pathwayId": null,
    "title": "Computer Science and Systems (BS)",
    "campusId": "uw-tacoma",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "high-confidence-needs-review",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is high confidence but still requires human/source-pipeline review before student visibility.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 231,
    "suggestedPrimary": {
      "url": "https://www.tacoma.uw.edu/set/programs/undergrad",
      "label": "Undergraduate Majors",
      "score": 70,
      "confidence": "high",
      "reasons": [
        "department requirements source role",
        "discovered from an official source page",
        "matches major keyword \"computer\"",
        "matches major keyword \"systems\"",
        "matches multiple major keywords",
        "official source text matches the selected major",
        "page title fetched successfully",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.tacoma.uw.edu/set/programs/undergrad",
        "label": "Undergraduate Majors",
        "score": 70,
        "confidence": "high",
        "reasons": [
          "department requirements source role",
          "discovered from an official source page",
          "matches major keyword \"computer\"",
          "matches major keyword \"systems\"",
          "matches multiple major keywords",
          "official source text matches the selected major",
          "page title fetched successfully",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/set/programs/undergrad/css",
        "label": "CSS Program Details",
        "score": 70,
        "confidence": "high",
        "reasons": [
          "department requirements source role",
          "discovered from an official source page",
          "matches major keyword \"computer\"",
          "matches major keyword \"systems\"",
          "matches multiple major keywords",
          "official source text matches the selected major",
          "page title fetched successfully",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/set/computer-science-and-systems",
        "label": "CSS Program Details",
        "score": 69,
        "confidence": "high",
        "reasons": [
          "department requirements source role",
          "discovered from an official source page",
          "matches major keyword \"computer\"",
          "matches major keyword \"systems\"",
          "matches multiple major keywords",
          "official source text matches the selected major",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "major",
    "ownerKey": "uw-tacoma-environmental-science",
    "planId": "uw-tacoma-environmental-science",
    "pathwayId": null,
    "title": "Environmental Science (BS)",
    "campusId": "uw-tacoma",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "medium-confidence",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is below the auto-promotion threshold; keep hidden until source discovery or parser support verifies it.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 121,
    "suggestedPrimary": {
      "url": "https://www.tacoma.uw.edu/registrar/graduation-requirements",
      "label": "graduation requirements",
      "score": 33,
      "confidence": "medium",
      "reasons": [
        "discovered from an official source page",
        "does not clearly mention the selected major",
        "generic campus requirements wording",
        "graduation requirements wording",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.tacoma.uw.edu/sias/sam/environmental-science",
        "label": "Scoped section: Electives for the General Environmental Science Option (29 credits)",
        "score": 60,
        "confidence": "high",
        "reasons": [
          "admissions wording",
          "already stored as an official source",
          "capstone-only wording",
          "curriculum wording",
          "elective list support source role",
          "explicit degree-requirements wording",
          "generic campus requirements wording",
          "graduation requirements wording",
          "matches major keyword \"environmental\"",
          "matches the selected degree route",
          "non-degree content wording",
          "official source text matches the selected major",
          "page title fetched successfully",
          "route-specific page may not cover every pathway in the selected major",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "verified against an official source candidate"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/sias/sam/environmental-science#permalink-211172",
        "label": "Admission Requirements",
        "score": 52,
        "confidence": "high",
        "reasons": [
          "admissions wording",
          "capstone-only wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "generic campus requirements wording",
          "graduation requirements wording",
          "matches major keyword \"environmental\"",
          "matches the selected degree route",
          "non-degree content wording",
          "non-schedulable course list source role",
          "official source text matches the selected major",
          "page title fetched successfully",
          "route-specific page may not cover every pathway in the selected major",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/sias/sam/environmental-sciences-capstone-agreement",
        "label": "Environmental Science Capstone Form",
        "score": 38,
        "confidence": "high",
        "reasons": [
          "capstone-only wording",
          "discovered from an official source page",
          "matches major keyword \"environmental\"",
          "non-schedulable course list source role",
          "official source text matches the selected major",
          "page title fetched successfully",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-tacoma-environmental-science:pathway:list-h-additional-courses-for-geoscience-option",
    "planId": "uw-tacoma-environmental-science",
    "pathwayId": "list-h-additional-courses-for-geoscience-option",
    "title": "Environmental Science (BS) - List H: Additional Courses for Geoscience Option",
    "campusId": "uw-tacoma",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "medium-confidence",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is below the auto-promotion threshold; keep hidden until source discovery or parser support verifies it.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 120,
    "suggestedPrimary": {
      "url": "https://www.tacoma.uw.edu/registrar/graduation-requirements",
      "label": "graduation requirements",
      "score": 33,
      "confidence": "medium",
      "reasons": [
        "discovered from an official source page",
        "does not clearly mention the selected major",
        "generic campus requirements wording",
        "graduation requirements wording",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.tacoma.uw.edu/sias/sam/environmental-science",
        "label": "Scoped section: Electives for the General Environmental Science Option (29 credits)",
        "score": 40,
        "confidence": "high",
        "reasons": [
          "admissions wording",
          "already stored as an official source",
          "capstone-only wording",
          "curriculum wording",
          "elective list support source role",
          "explicit degree-requirements wording",
          "generic campus requirements wording",
          "graduation requirements wording",
          "matches major keyword \"courses\"",
          "matches major keyword \"environmental\"",
          "matches major keyword \"for\"",
          "matches multiple major keywords",
          "matches the selected degree route",
          "non-degree content wording",
          "page title fetched successfully",
          "specific bachelor route wording",
          "stays on an official UW domain"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/sias/sam/environmental-science#permalink-211172",
        "label": "Admission Requirements",
        "score": 38,
        "confidence": "high",
        "reasons": [
          "admissions wording",
          "capstone-only wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "generic campus requirements wording",
          "graduation requirements wording",
          "matches major keyword \"courses\"",
          "matches major keyword \"environmental\"",
          "matches major keyword \"for\"",
          "matches multiple major keywords",
          "matches the selected degree route",
          "non-degree content wording",
          "non-schedulable course list source role",
          "page title fetched successfully",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/registrar/graduation-requirements",
        "label": "graduation requirements",
        "score": 33,
        "confidence": "medium",
        "reasons": [
          "discovered from an official source page",
          "does not clearly mention the selected major",
          "generic campus requirements wording",
          "graduation requirements wording",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "major",
    "ownerKey": "uw-tacoma-environmental-sustainability",
    "planId": "uw-tacoma-environmental-sustainability",
    "pathwayId": null,
    "title": "Environmental Sustainability (BA)",
    "campusId": "uw-tacoma",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "medium-confidence",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is below the auto-promotion threshold; keep hidden until source discovery or parser support verifies it.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 117,
    "suggestedPrimary": {
      "url": "https://www.tacoma.uw.edu/registrar/graduation-requirements",
      "label": "graduation requirements",
      "score": 33,
      "confidence": "medium",
      "reasons": [
        "discovered from an official source page",
        "does not clearly mention the selected major",
        "generic campus requirements wording",
        "graduation requirements wording",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.tacoma.uw.edu/sias/sam/environmental-sustainability",
        "label": "Scoped section: Environmental Policy and Law Option (20 credits)",
        "score": 82,
        "confidence": "high",
        "reasons": [
          "admissions wording",
          "advising wording",
          "already stored as an official source",
          "curriculum wording",
          "explicit degree-requirements wording",
          "generic campus requirements wording",
          "graduation requirements wording",
          "matches major keyword \"environmental\"",
          "matches major keyword \"sustainability\"",
          "matches multiple major keywords",
          "matches the selected degree route",
          "official source text matches the selected major",
          "official support source role",
          "page title fetched successfully",
          "route-specific page may not cover every pathway in the selected major",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "verified against an official source candidate"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/sias/sam/environmental-sustainability#permalink-213883",
        "label": "Admission Requirements",
        "score": 78,
        "confidence": "high",
        "reasons": [
          "admissions wording",
          "advising wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "generic campus requirements wording",
          "graduation requirements wording",
          "matches major keyword \"environmental\"",
          "matches major keyword \"sustainability\"",
          "matches multiple major keywords",
          "matches the selected degree route",
          "official source text matches the selected major",
          "official support source role",
          "page title fetched successfully",
          "route-specific page may not cover every pathway in the selected major",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/registrar/graduation-requirements",
        "label": "graduation requirements",
        "score": 33,
        "confidence": "medium",
        "reasons": [
          "discovered from an official source page",
          "does not clearly mention the selected major",
          "generic campus requirements wording",
          "graduation requirements wording",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-tacoma-environmental-sustainability:pathway:business-nonprofit-leadership-option",
    "planId": "uw-tacoma-environmental-sustainability",
    "pathwayId": "business-nonprofit-leadership-option",
    "title": "Environmental Sustainability (BA) - Business and Nonprofit Leadership option",
    "campusId": "uw-tacoma",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "medium-confidence",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is below the auto-promotion threshold; keep hidden until source discovery or parser support verifies it.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 117,
    "suggestedPrimary": {
      "url": "https://www.tacoma.uw.edu/registrar/graduation-requirements",
      "label": "graduation requirements",
      "score": 33,
      "confidence": "medium",
      "reasons": [
        "discovered from an official source page",
        "does not clearly mention the selected major",
        "generic campus requirements wording",
        "graduation requirements wording",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.tacoma.uw.edu/sias/sam/environmental-sustainability#permalink-213883",
        "label": "Admission Requirements",
        "score": 56,
        "confidence": "medium",
        "reasons": [
          "admissions wording",
          "advising wording",
          "curriculum wording",
          "discovered from an official source page",
          "explicit degree-requirements wording",
          "generic campus requirements wording",
          "graduation requirements wording",
          "matches major keyword \"environmental\"",
          "matches major keyword \"sustainability\"",
          "matches multiple major keywords",
          "matches the selected degree route",
          "official support source role",
          "page title fetched successfully",
          "specific bachelor route wording",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/sias/sam/environmental-sustainability",
        "label": "Scoped section: Environmental Policy and Law Option (20 credits)",
        "score": 54,
        "confidence": "medium",
        "reasons": [
          "admissions wording",
          "advising wording",
          "already stored as an official source",
          "curriculum wording",
          "explicit degree-requirements wording",
          "generic campus requirements wording",
          "graduation requirements wording",
          "matches major keyword \"environmental\"",
          "matches major keyword \"sustainability\"",
          "matches multiple major keywords",
          "matches the selected degree route",
          "official support source role",
          "page title fetched successfully",
          "specific bachelor route wording",
          "stays on an official UW domain"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/registrar/graduation-requirements",
        "label": "graduation requirements",
        "score": 33,
        "confidence": "medium",
        "reasons": [
          "discovered from an official source page",
          "does not clearly mention the selected major",
          "generic campus requirements wording",
          "graduation requirements wording",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "major",
    "ownerKey": "uw-tacoma-history",
    "planId": "uw-tacoma-history",
    "pathwayId": null,
    "title": "History (BA)",
    "campusId": "uw-tacoma",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "medium-confidence",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is below the auto-promotion threshold; keep hidden until source discovery or parser support verifies it.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 112,
    "suggestedPrimary": {
      "url": "https://www.tacoma.uw.edu/registrar/graduation-requirements",
      "label": "graduation requirements",
      "score": 33,
      "confidence": "medium",
      "reasons": [
        "discovered from an official source page",
        "does not clearly mention the selected major",
        "generic campus requirements wording",
        "graduation requirements wording",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.tacoma.uw.edu/sias/socs/general-history-option",
        "label": "General History Option",
        "score": 52,
        "confidence": "high",
        "reasons": [
          "advising wording",
          "already stored as an official source",
          "elective list support source role",
          "explicit degree-requirements wording",
          "matches major keyword \"history\"",
          "non-degree content wording",
          "official source path matches the selected major",
          "page title fetched successfully",
          "stays on an official UW domain",
          "verified against an official source candidate"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/sias/socs/general-history-option#main-content",
        "label": "Skip to main content",
        "score": 48,
        "confidence": "high",
        "reasons": [
          "advising wording",
          "discovered from an official source page",
          "elective list support source role",
          "explicit degree-requirements wording",
          "matches major keyword \"history\"",
          "non-degree content wording",
          "official source path matches the selected major",
          "page title fetched successfully",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/registrar/graduation-requirements",
        "label": "graduation requirements",
        "score": 33,
        "confidence": "medium",
        "reasons": [
          "discovered from an official source page",
          "does not clearly mention the selected major",
          "generic campus requirements wording",
          "graduation requirements wording",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      }
    ]
  },
  {
    "ownerType": "pathway",
    "ownerKey": "uw-tacoma-history:pathway:general-history-option-department-of-social-sciences-university-of-washington-tacoma",
    "planId": "uw-tacoma-history",
    "pathwayId": "general-history-option-department-of-social-sciences-university-of-washington-tacoma",
    "title": "History (BA) - General History option Department of Social Sciences University of Washington Tacoma",
    "campusId": "uw-tacoma",
    "sourceCoverageStatus": "parser-unsupported",
    "reviewStatus": "medium-confidence",
    "studentVisibility": "hidden",
    "sourceGapReason": "Official primary-source candidate is below the auto-promotion threshold; keep hidden until source discovery or parser support verifies it.",
    "generatedAt": "2026-05-15T23:55:41.821Z",
    "officialLinkCount": 1,
    "candidateCount": 113,
    "suggestedPrimary": {
      "url": "https://www.tacoma.uw.edu/sias/academic-programs",
      "label": "major requirements",
      "score": 69,
      "confidence": "medium",
      "reasons": [
        "discovered from an official source page",
        "explicit major-requirements wording",
        "matches major keyword \"tacoma\"",
        "primary degree requirements source role",
        "stays on an official UW domain",
        "stays on the same department or school page"
      ]
    },
    "sourceDiscoveryAttempts": [
      {
        "url": "https://www.tacoma.uw.edu/sias/academic-programs",
        "label": "major requirements",
        "score": 69,
        "confidence": "medium",
        "reasons": [
          "discovered from an official source page",
          "explicit major-requirements wording",
          "matches major keyword \"tacoma\"",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/sias/all-sias-majors-minors",
        "label": "major requirements",
        "score": 69,
        "confidence": "medium",
        "reasons": [
          "discovered from an official source page",
          "explicit major-requirements wording",
          "matches major keyword \"tacoma\"",
          "primary degree requirements source role",
          "stays on an official UW domain",
          "stays on the same department or school page"
        ]
      },
      {
        "url": "https://www.tacoma.uw.edu/sias/socs/general-history-option",
        "label": "General History Option",
        "score": 68,
        "confidence": "high",
        "reasons": [
          "advising wording",
          "already stored as an official source",
          "elective list support source role",
          "explicit degree-requirements wording",
          "explicitly names the selected pathway or route",
          "matches major keyword \"department\"",
          "matches major keyword \"general\"",
          "matches major keyword \"history\"",
          "matches major keyword \"social\"",
          "matches major keyword \"tacoma\"",
          "matches major keyword \"university\"",
          "matches major keyword \"washington\"",
          "matches multiple major keywords",
          "non-degree content wording",
          "official source text matches the selected pathway",
          "page title fetched successfully",
          "stays on an official UW domain",
          "verified against an official source candidate"
        ]
      }
    ]
  }
];
