/* eslint-disable */
/* auto-generated by scripts/planner/generate-transfer-planner-student-runtime.cjs */

import type {
  TransferPlannerCampus,
  TransferPlannerMajorPathway,
  TransferPlannerMajorPlan,
  TransferPlannerResolvedMajorPlan,
  TransferPlannerTrack,
} from "../transfer-planner-types";
import type {
  TransferPlannerCourseRegistryEntry,
  TransferPlannerEquivalencyRule,
  TransferPlannerParsedRequirementAtomCandidate,
  TransferPlannerParsedRequirementSourceBlock,
  TransferPlannerRequirementSupportList,
  TransferPlannerSourceManifestEntry,
} from "./schema";

export type TransferPlannerRuntimeCompactCourseRegistryEntry = Pick<
  TransferPlannerCourseRegistryEntry,
  | "schoolId"
  | "code"
  | "title"
  | "creditValue"
  | "creditLabel"
  | "catalogDescription"
  | "prerequisiteCourseCodes"
  | "prerequisiteAlternativeCourseCodeSets"
  | "corequisiteCourseCodes"
  | "corequisiteAlternativeCourseCodeSets"
  | "latestAvailabilitySummary"
  | "latestPublishedQuarters"
>;

export type TransferPlannerRuntimeParsedRequirementAtomCandidate = Pick<
  TransferPlannerParsedRequirementAtomCandidate,
  "uwCourseCode" | "sourceLineHints"
> & {
  title?: string | null;
};

export type TransferPlannerRuntimeParsedRequirementSourceBlock = Pick<
  TransferPlannerParsedRequirementSourceBlock,
  | "id"
  | "ownerId"
  | "ownerTitle"
  | "planId"
  | "pathwayId"
  | "primarySourceUrl"
  | "primarySourceLabel"
  | "sourceUrl"
  | "coveredSourceUrls"
  | "sourceLabel"
  | "sourceRole"
  | "sourceRoleStatus"
  | "canCreateSchedulableRows"
  | "sourceScope"
  | "canCreateRequiredRows"
  | "canCreateOptionGroups"
  | "canCreateCreditBuckets"
  | "canCreateCategoryOptions"
  | "canCreateApprovedFilters"
  | "canCreateElectiveLists"
  | "canCreateSequencingHints"
  | "canCreateAdmissionPrepRows"
  | "canCreateScheduleRows"
  | "supportOnly"
  | "nonSchedulable"
  | "requirementShape"
  | "requirementCueLines"
  | "parsedUwCourseCodes"
  | "approvedFilterUwCourseCodes"
  | "electiveListUwCourseCodes"
  | "supportOnlyUwCourseCodes"
  | "supportLists"
> & {
  parsedRequirementAtomCandidates: TransferPlannerRuntimeParsedRequirementAtomCandidate[];
  parsedRequirementCourses?: TransferPlannerParsedRequirementSourceBlock["parsedRequirementCourses"];
  parsedDegreeMapBlockCandidates?: TransferPlannerParsedRequirementSourceBlock["parsedDegreeMapBlockCandidates"];
  parsedRequirementGroups?: TransferPlannerParsedRequirementSourceBlock["parsedRequirementGroups"];
  supportLists?: TransferPlannerRequirementSupportList[];
};

const { TRANSFER_PLANNER_RUNTIME_CAMPUSES_VALUE } = require("./student-runtime.generated/campuses.generated");
export const TRANSFER_PLANNER_RUNTIME_CAMPUSES = TRANSFER_PLANNER_RUNTIME_CAMPUSES_VALUE as TransferPlannerCampus[];

const { TRANSFER_PLANNER_RUNTIME_TRACKS_VALUE } = require("./student-runtime.generated/tracks.generated");
export const TRANSFER_PLANNER_RUNTIME_TRACKS = TRANSFER_PLANNER_RUNTIME_TRACKS_VALUE as TransferPlannerTrack[];

const { TRANSFER_PLANNER_RUNTIME_MAJOR_PLANS_VALUE } = require("./student-runtime.generated/major-plans.generated");
export const TRANSFER_PLANNER_RUNTIME_MAJOR_PLANS = TRANSFER_PLANNER_RUNTIME_MAJOR_PLANS_VALUE as TransferPlannerMajorPlan[];

const { TRANSFER_PLANNER_RUNTIME_PATHWAYS_BY_PLAN_ID_VALUE } = require("./student-runtime.generated/pathways-by-plan-id.generated");
export const TRANSFER_PLANNER_RUNTIME_PATHWAYS_BY_PLAN_ID = TRANSFER_PLANNER_RUNTIME_PATHWAYS_BY_PLAN_ID_VALUE as Record<string, TransferPlannerMajorPathway[]>;

const { TRANSFER_PLANNER_RUNTIME_RESOLVED_MAJOR_PLANS_BY_KEY_VALUE } = require("./student-runtime.generated/resolved-major-plans-by-key.generated");
export const TRANSFER_PLANNER_RUNTIME_RESOLVED_MAJOR_PLANS_BY_KEY = TRANSFER_PLANNER_RUNTIME_RESOLVED_MAJOR_PLANS_BY_KEY_VALUE as Record<string, TransferPlannerResolvedMajorPlan>;

const { TRANSFER_PLANNER_RUNTIME_PRIMARY_DEGREE_SOURCES_BY_KEY_VALUE } = require("./student-runtime.generated/primary-degree-sources-by-key.generated");
export const TRANSFER_PLANNER_RUNTIME_PRIMARY_DEGREE_SOURCES_BY_KEY = TRANSFER_PLANNER_RUNTIME_PRIMARY_DEGREE_SOURCES_BY_KEY_VALUE as Record<string, TransferPlannerSourceManifestEntry>;

const { TRANSFER_PLANNER_RUNTIME_COMPACT_COURSE_REGISTRY_VALUE } = require("./student-runtime.generated/compact-course-registry.generated");
export const TRANSFER_PLANNER_RUNTIME_COMPACT_COURSE_REGISTRY = TRANSFER_PLANNER_RUNTIME_COMPACT_COURSE_REGISTRY_VALUE as TransferPlannerRuntimeCompactCourseRegistryEntry[];

const { TRANSFER_PLANNER_RUNTIME_EQUIVALENCY_RULE_REGISTRY_VALUE } = require("./student-runtime.generated/equivalency-rule-registry.generated");
export const TRANSFER_PLANNER_RUNTIME_EQUIVALENCY_RULE_REGISTRY = TRANSFER_PLANNER_RUNTIME_EQUIVALENCY_RULE_REGISTRY_VALUE as TransferPlannerEquivalencyRule[];

const { TRANSFER_PLANNER_RUNTIME_PARSED_REQUIREMENT_SOURCE_BLOCK_REGISTRY_VALUE } = require("./student-runtime.generated/parsed-requirement-source-block-registry.generated");
export const TRANSFER_PLANNER_RUNTIME_PARSED_REQUIREMENT_SOURCE_BLOCK_REGISTRY = TRANSFER_PLANNER_RUNTIME_PARSED_REQUIREMENT_SOURCE_BLOCK_REGISTRY_VALUE as TransferPlannerRuntimeParsedRequirementSourceBlock[];

const { TRANSFER_PLANNER_RUNTIME_SOURCE_GAP_REGISTRY_VALUE } = require("./student-runtime.generated/source-gap-registry.generated");
export const TRANSFER_PLANNER_RUNTIME_SOURCE_GAP_REGISTRY = TRANSFER_PLANNER_RUNTIME_SOURCE_GAP_REGISTRY_VALUE as Array<{ planId: string; pathwayId: string | null; [key: string]: unknown }>;

