/* eslint-disable */
/* auto-generated by scripts/planner/generate-transfer-planner-student-runtime.cjs */

const TRANSFER_PLANNER_RUNTIME_CAMPUSES_JSON = "[{\"id\":\"uw-bothell\",\"title\":\"UW Bothell\",\"summary\":\"Source-generated from parsed UW requirement-source registries.\",\"officialLinks\":[]},{\"id\":\"uw-seattle\",\"title\":\"UW Seattle\",\"summary\":\"Source-generated from parsed UW requirement-source registries.\",\"officialLinks\":[]},{\"id\":\"uw-tacoma\",\"title\":\"UW Tacoma\",\"summary\":\"Source-generated from parsed UW requirement-source registries.\",\"officialLinks\":[]}]";
export const TRANSFER_PLANNER_RUNTIME_CAMPUSES_VALUE = JSON.parse(TRANSFER_PLANNER_RUNTIME_CAMPUSES_JSON);

