/* eslint-disable */
/* auto-generated by scripts/planner/generate-transfer-planner-student-runtime.cjs */

const TRANSFER_PLANNER_RUNTIME_SOURCE_GAP_REGISTRY_JSON = "[]";
export const TRANSFER_PLANNER_RUNTIME_SOURCE_GAP_REGISTRY_VALUE = JSON.parse(TRANSFER_PLANNER_RUNTIME_SOURCE_GAP_REGISTRY_JSON);

