/* eslint-disable */
/* auto-generated by scripts/planner/generate-transfer-planner-student-runtime.cjs */

const TRANSFER_PLANNER_RUNTIME_SOURCE_GAP_REGISTRY_JSON = "[{\"ownerType\":\"major\",\"ownerKey\":\"uw-bothell-chemistry-biochemistry\",\"planId\":\"uw-bothell-chemistry-biochemistry\",\"pathwayId\":null,\"title\":\"Chemistry: Biochemistry (BS)\",\"campusId\":\"uw-bothell\",\"sourceCoverageStatus\":\"source-unfindable\",\"reviewStatus\":\"needs-source-automation\",\"studentVisibility\":\"hidden\",\"sourceGapReason\":\"No official primary degree-requirements source candidate met the minimum discovery threshold.\",\"generatedAt\":\"2026-05-21T15:57:04.779Z\",\"officialLinkCount\":0,\"candidateCount\":0,\"suggestedPrimary\":null,\"sourceDiscoveryAttempts\":[]}]";
export const TRANSFER_PLANNER_RUNTIME_SOURCE_GAP_REGISTRY_VALUE = JSON.parse(TRANSFER_PLANNER_RUNTIME_SOURCE_GAP_REGISTRY_JSON);

